package mybatis.mapper;

import java.util.List;
import mybatis.model.ActivityMembers;
import mybatis.model.ActivityMembersExample;
import org.apache.ibatis.annotations.Param;

public interface ActivityMembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_members
     *
     * @mbggenerated
     */
    int countByExample(ActivityMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_members
     *
     * @mbggenerated
     */
    int deleteByExample(ActivityMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_members
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_members
     *
     * @mbggenerated
     */
    int insert(ActivityMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_members
     *
     * @mbggenerated
     */
    int insertSelective(ActivityMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_members
     *
     * @mbggenerated
     */
    List<ActivityMembers> selectByExample(ActivityMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_members
     *
     * @mbggenerated
     */
    ActivityMembers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_members
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ActivityMembers record, @Param("example") ActivityMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_members
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ActivityMembers record, @Param("example") ActivityMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_members
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ActivityMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_members
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ActivityMembers record);
}