package mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import mybatis.model.BookBorrowRecord;
import mybatis.model.BookBorrowRecordExample;

public interface BookBorrowRecordMapper {
	
	List<BookBorrowRecord> selectBorrowByName(String name);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_borrow_record
     *
     * @mbggenerated
     */
    int countByExample(BookBorrowRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_borrow_record
     *
     * @mbggenerated
     */
    int deleteByExample(BookBorrowRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_borrow_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_borrow_record
     *
     * @mbggenerated
     */
    int insert(BookBorrowRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_borrow_record
     *
     * @mbggenerated
     */
    int insertSelective(BookBorrowRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_borrow_record
     *
     * @mbggenerated
     */
    List<BookBorrowRecord> selectByExample(BookBorrowRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_borrow_record
     *
     * @mbggenerated
     */
    BookBorrowRecord selectByPrimaryKey(Integer bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_borrow_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BookBorrowRecord record, @Param("example") BookBorrowRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_borrow_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BookBorrowRecord record, @Param("example") BookBorrowRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_borrow_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BookBorrowRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_borrow_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BookBorrowRecord record);
}