package mybatis.mapper;

import java.util.List;
import mybatis.model.ProjectMembers;
import mybatis.model.ProjectMembersExample;
import org.apache.ibatis.annotations.Param;

public interface ProjectMembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbggenerated
     */
    int countByExample(ProjectMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbggenerated
     */
    int deleteByExample(ProjectMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbggenerated
     */
    int insert(ProjectMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbggenerated
     */
    int insertSelective(ProjectMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbggenerated
     */
    List<ProjectMembers> selectByExample(ProjectMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbggenerated
     */
    ProjectMembers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProjectMembers record, @Param("example") ProjectMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProjectMembers record, @Param("example") ProjectMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProjectMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProjectMembers record);

    /**
     * 通过发布人账号获取发布人发布的所有项目的报名记录
     * @param publisher
     * @return
     */
    List<ProjectMembers> getApplyerList(@Param("publisher") String publisher);
}