package mybatis.mapper;

import java.util.List;
import mybatis.model.SupplyBorrowRecord;
import mybatis.model.SupplyBorrowRecordExample;
import org.apache.ibatis.annotations.Param;

public interface SupplyBorrowRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_borrow_record
     *
     * @mbggenerated
     */
    int countByExample(SupplyBorrowRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_borrow_record
     *
     * @mbggenerated
     */
    int deleteByExample(SupplyBorrowRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_borrow_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer supplyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_borrow_record
     *
     * @mbggenerated
     */
    int insert(SupplyBorrowRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_borrow_record
     *
     * @mbggenerated
     */
    int insertSelective(SupplyBorrowRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_borrow_record
     *
     * @mbggenerated
     */
    List<SupplyBorrowRecord> selectByExample(SupplyBorrowRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_borrow_record
     *
     * @mbggenerated
     */
    SupplyBorrowRecord selectByPrimaryKey(Integer supplyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_borrow_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SupplyBorrowRecord record, @Param("example") SupplyBorrowRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_borrow_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SupplyBorrowRecord record, @Param("example") SupplyBorrowRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_borrow_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SupplyBorrowRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_borrow_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SupplyBorrowRecord record);
}