package mybatis.mapper;

import java.util.List;
import mybatis.model.SysActivity;
import mybatis.model.SysActivityExample;
import org.apache.ibatis.annotations.Param;

public interface SysActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_activity
     *
     * @mbggenerated
     */
    int countByExample(SysActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_activity
     *
     * @mbggenerated
     */
    int deleteByExample(SysActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_activity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_activity
     *
     * @mbggenerated
     */
    int insert(SysActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_activity
     *
     * @mbggenerated
     */
    int insertSelective(SysActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_activity
     *
     * @mbggenerated
     */
    List<SysActivity> selectByExample(SysActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_activity
     *
     * @mbggenerated
     */
    SysActivity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_activity
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysActivity record, @Param("example") SysActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_activity
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysActivity record, @Param("example") SysActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_activity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_activity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysActivity record);

    /**
     * 获得我参加的活动列表
     * @param activityAccount
     * @return
     */
    List<SysActivity> getMyActivityList(String activityAccount);
}