package mybatis.mapper;

import java.util.List;
import mybatis.model.SysBook;
import mybatis.model.SysBookExample;
import org.apache.ibatis.annotations.Param;

public interface SysBookMapper {
	List<SysBook> allAppRecByWord(@Param("start") int start, @Param("limit") int limit, @Param("word") String word);
	List<SysBook> allAppRec(@Param("start") int start, @Param("limit") int limit);
	int countMyAppRec(String account);
	int countMyAppRecByWord(@Param("account") String account, @Param("word") String word);
	
	int countAllAppRecByWord(String word);
	int countAllAppRec();
	
	int countAllBorrowByWord(String name);
	int countAllBorrow();
	/**
	 * 
	 * @param name
	 * @param account
	 * @return
	 */
	int countByWordAndAccount(@Param("account") String account, @Param("name") String name);
	/**
	 * 
	 * @param account
	 * @return
	 */
	int countMe(String account);
	
	int countPart(String name);
	
	int count();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    int countByExample(SysBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    int deleteByExample(SysBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    int insert(SysBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    int insertSelective(SysBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    List<SysBook> selectByExample(SysBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    SysBook selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysBook record, @Param("example") SysBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysBook record, @Param("example") SysBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysBook record);
}