package mybatis.mapper;

import java.util.List;
import mybatis.model.SysGraduateDuty;
import mybatis.model.SysGraduateDutyExample;
import org.apache.ibatis.annotations.Param;

public interface SysGraduateDutyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_graduate_duty
     *
     * @mbggenerated
     */
    int countByExample(SysGraduateDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_graduate_duty
     *
     * @mbggenerated
     */
    int deleteByExample(SysGraduateDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_graduate_duty
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_graduate_duty
     *
     * @mbggenerated
     */
    int insert(SysGraduateDuty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_graduate_duty
     *
     * @mbggenerated
     */
    int insertSelective(SysGraduateDuty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_graduate_duty
     *
     * @mbggenerated
     */
    List<SysGraduateDuty> selectByExample(SysGraduateDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_graduate_duty
     *
     * @mbggenerated
     */
    SysGraduateDuty selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_graduate_duty
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysGraduateDuty record, @Param("example") SysGraduateDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_graduate_duty
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysGraduateDuty record, @Param("example") SysGraduateDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_graduate_duty
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysGraduateDuty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_graduate_duty
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysGraduateDuty record);

}