package mybatis.mapper;

import java.util.List;
import mybatis.model.SysGroup;
import mybatis.model.SysGroupExample;
import org.apache.ibatis.annotations.Param;

public interface SysGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbggenerated
     */
    int countByExample(SysGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbggenerated
     */
    int deleteByExample(SysGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbggenerated
     */
    int insert(SysGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbggenerated
     */
    int insertSelective(SysGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbggenerated
     */
    List<SysGroup> selectByExample(SysGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbggenerated
     */
    SysGroup selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysGroup record, @Param("example") SysGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysGroup record, @Param("example") SysGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysGroup record);
}