package mybatis.mapper;

import java.util.List;
import mybatis.model.SysHealthHead;
import mybatis.model.SysHealthHeadExample;
import org.apache.ibatis.annotations.Param;

public interface SysHealthHeadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_health_head
     *
     * @mbggenerated
     */
    int countByExample(SysHealthHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_health_head
     *
     * @mbggenerated
     */
    int deleteByExample(SysHealthHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_health_head
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_health_head
     *
     * @mbggenerated
     */
    int insert(SysHealthHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_health_head
     *
     * @mbggenerated
     */
    int insertSelective(SysHealthHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_health_head
     *
     * @mbggenerated
     */
    List<SysHealthHead> selectByExample(SysHealthHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_health_head
     *
     * @mbggenerated
     */
    SysHealthHead selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_health_head
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysHealthHead record, @Param("example") SysHealthHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_health_head
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysHealthHead record, @Param("example") SysHealthHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_health_head
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysHealthHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_health_head
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysHealthHead record);

    /**
     * 批量插入
     * @param sysHealthHeadList
     * @return
     */
    int insertList(List<SysHealthHead> sysHealthHeadList);
}