package mybatis.mapper;

import java.util.List;
import mybatis.model.SysHealthHeadDate;
import mybatis.model.SysHealthHeadDateExample;
import org.apache.ibatis.annotations.Param;

public interface SysHealthHeadDateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_health_head_date
     *
     * @mbggenerated
     */
    int countByExample(SysHealthHeadDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_health_head_date
     *
     * @mbggenerated
     */
    int deleteByExample(SysHealthHeadDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_health_head_date
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_health_head_date
     *
     * @mbggenerated
     */
    int insert(SysHealthHeadDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_health_head_date
     *
     * @mbggenerated
     */
    int insertSelective(SysHealthHeadDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_health_head_date
     *
     * @mbggenerated
     */
    List<SysHealthHeadDate> selectByExample(SysHealthHeadDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_health_head_date
     *
     * @mbggenerated
     */
    SysHealthHeadDate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_health_head_date
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysHealthHeadDate record, @Param("example") SysHealthHeadDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_health_head_date
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysHealthHeadDate record, @Param("example") SysHealthHeadDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_health_head_date
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysHealthHeadDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_health_head_date
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysHealthHeadDate record);
}