package mybatis.mapper;

import java.util.List;
import mybatis.model.SysMeetingroom;
import mybatis.model.SysMeetingroomExample;
import org.apache.ibatis.annotations.Param;

public interface SysMeetingroomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_meetingroom
     *
     * @mbggenerated
     */
    int countByExample(SysMeetingroomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_meetingroom
     *
     * @mbggenerated
     */
    int deleteByExample(SysMeetingroomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_meetingroom
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_meetingroom
     *
     * @mbggenerated
     */
    int insert(SysMeetingroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_meetingroom
     *
     * @mbggenerated
     */
    int insertSelective(SysMeetingroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_meetingroom
     *
     * @mbggenerated
     */
    List<SysMeetingroom> selectByExample(SysMeetingroomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_meetingroom
     *
     * @mbggenerated
     */
    SysMeetingroom selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_meetingroom
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysMeetingroom record, @Param("example") SysMeetingroomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_meetingroom
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysMeetingroom record, @Param("example") SysMeetingroomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_meetingroom
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysMeetingroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_meetingroom
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysMeetingroom record);

    /**
     * 批量插入
     */
    int insertList(List<SysMeetingroom> list);
}