package mybatis.mapper;

import java.util.List;
import mybatis.model.SysTask;
import mybatis.model.SysTaskExample;
import org.apache.ibatis.annotations.Param;

public interface SysTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    int countByExample(SysTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    int deleteByExample(SysTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    int insert(SysTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    int insertSelective(SysTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    List<SysTask> selectByExample(SysTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    SysTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysTask record, @Param("example") SysTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysTask record, @Param("example") SysTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysTask record);
}