package mybatis.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table project_members
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class ProjectMembers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_members.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   项目编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_members.project_id
     *
     * @mbggenerated
     */
    private Integer projectId;

    /**
     * Database Column Remarks:
     *   申请人账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_members.project_account
     *
     * @mbggenerated
     */
    private String projectAccount;

    /**
     * Database Column Remarks:
     *   申请状态 0待审核/1通过/-1淘汰
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_members.pm_status
     *
     * @mbggenerated
     */

    private Integer pmStatus;

    /**
     * Database Column Remarks:
     *   申请加入项目的介绍(简历)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_members.pm_reason
     *
     * @mbggenerated
     */
    private String pmReason;

    /**
     * Database Column Remarks:
     *   申请日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_members.pm_time
     *
     * @mbggenerated
     */
    private Date pmTime;

    /**
     * 申请人姓名
     */
    private String userName;

    private String pmTimeStr;

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPmTimeStr() {
        return pmTimeStr;
    }

    public void setPmTimeStr(String pmTimeStr) {
        this.pmTimeStr = pmTimeStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_members.id
     *
     * @return the value of project_members.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_members.id
     *
     * @param id the value for project_members.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_members.project_id
     *
     * @return the value of project_members.project_id
     *
     * @mbggenerated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_members.project_id
     *
     * @param projectId the value for project_members.project_id
     *
     * @mbggenerated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_members.project_account
     *
     * @return the value of project_members.project_account
     *
     * @mbggenerated
     */
    public String getProjectAccount() {
        return projectAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_members.project_account
     *
     * @param projectAccount the value for project_members.project_account
     *
     * @mbggenerated
     */
    public void setProjectAccount(String projectAccount) {
        this.projectAccount = projectAccount == null ? null : projectAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_members.pm_status
     *
     * @return the value of project_members.pm_status
     *
     * @mbggenerated
     */
    public Integer getPmStatus() {
        return pmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_members.pm_status
     *
     * @param pmStatus the value for project_members.pm_status
     *
     * @mbggenerated
     */
    public void setPmStatus(Integer pmStatus) {
        this.pmStatus = pmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_members.pm_reason
     *
     * @return the value of project_members.pm_reason
     *
     * @mbggenerated
     */
    public String getPmReason() {
        return pmReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_members.pm_reason
     *
     * @param pmReason the value for project_members.pm_reason
     *
     * @mbggenerated
     */
    public void setPmReason(String pmReason) {
        this.pmReason = pmReason == null ? null : pmReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_members.pm_time
     *
     * @return the value of project_members.pm_time
     *
     * @mbggenerated
     */
    public Date getPmTime() {
        return pmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_members.pm_time
     *
     * @param pmTime the value for project_members.pm_time
     *
     * @mbggenerated
     */
    public void setPmTime(Date pmTime) {
        this.pmTime = pmTime;
    }
}