package mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ProjectMembersExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_members
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_members
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_members
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbggenerated
     */
    public ProjectMembersExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_members
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Integer value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Integer value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Integer value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Integer value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Integer value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Integer> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Integer> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Integer value1, Integer value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNull() {
            addCriterion("project_name is null");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNotNull() {
            addCriterion("project_name is not null");
            return (Criteria) this;
        }

        public Criteria andProjectNameEqualTo(String value) {
            addCriterion("project_name =", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotEqualTo(String value) {
            addCriterion("project_name <>", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThan(String value) {
            addCriterion("project_name >", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("project_name >=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThan(String value) {
            addCriterion("project_name <", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThanOrEqualTo(String value) {
            addCriterion("project_name <=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLike(String value) {
            addCriterion("project_name like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotLike(String value) {
            addCriterion("project_name not like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameIn(List<String> values) {
            addCriterion("project_name in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotIn(List<String> values) {
            addCriterion("project_name not in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameBetween(String value1, String value2) {
            addCriterion("project_name between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotBetween(String value1, String value2) {
            addCriterion("project_name not between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectAccountIsNull() {
            addCriterion("project_account is null");
            return (Criteria) this;
        }

        public Criteria andProjectAccountIsNotNull() {
            addCriterion("project_account is not null");
            return (Criteria) this;
        }

        public Criteria andProjectAccountEqualTo(String value) {
            addCriterion("project_account =", value, "projectAccount");
            return (Criteria) this;
        }

        public Criteria andProjectAccountNotEqualTo(String value) {
            addCriterion("project_account <>", value, "projectAccount");
            return (Criteria) this;
        }

        public Criteria andProjectAccountGreaterThan(String value) {
            addCriterion("project_account >", value, "projectAccount");
            return (Criteria) this;
        }

        public Criteria andProjectAccountGreaterThanOrEqualTo(String value) {
            addCriterion("project_account >=", value, "projectAccount");
            return (Criteria) this;
        }

        public Criteria andProjectAccountLessThan(String value) {
            addCriterion("project_account <", value, "projectAccount");
            return (Criteria) this;
        }

        public Criteria andProjectAccountLessThanOrEqualTo(String value) {
            addCriterion("project_account <=", value, "projectAccount");
            return (Criteria) this;
        }

        public Criteria andProjectAccountLike(String value) {
            addCriterion("project_account like", value, "projectAccount");
            return (Criteria) this;
        }

        public Criteria andProjectAccountNotLike(String value) {
            addCriterion("project_account not like", value, "projectAccount");
            return (Criteria) this;
        }

        public Criteria andProjectAccountIn(List<String> values) {
            addCriterion("project_account in", values, "projectAccount");
            return (Criteria) this;
        }

        public Criteria andProjectAccountNotIn(List<String> values) {
            addCriterion("project_account not in", values, "projectAccount");
            return (Criteria) this;
        }

        public Criteria andProjectAccountBetween(String value1, String value2) {
            addCriterion("project_account between", value1, value2, "projectAccount");
            return (Criteria) this;
        }

        public Criteria andProjectAccountNotBetween(String value1, String value2) {
            addCriterion("project_account not between", value1, value2, "projectAccount");
            return (Criteria) this;
        }

        public Criteria andPmStatusIsNull() {
            addCriterion("pm_status is null");
            return (Criteria) this;
        }

        public Criteria andPmStatusIsNotNull() {
            addCriterion("pm_status is not null");
            return (Criteria) this;
        }

        public Criteria andPmStatusEqualTo(Integer value) {
            addCriterion("pm_status =", value, "pmStatus");
            return (Criteria) this;
        }

        public Criteria andPmStatusNotEqualTo(Integer value) {
            addCriterion("pm_status <>", value, "pmStatus");
            return (Criteria) this;
        }

        public Criteria andPmStatusGreaterThan(Integer value) {
            addCriterion("pm_status >", value, "pmStatus");
            return (Criteria) this;
        }

        public Criteria andPmStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("pm_status >=", value, "pmStatus");
            return (Criteria) this;
        }

        public Criteria andPmStatusLessThan(Integer value) {
            addCriterion("pm_status <", value, "pmStatus");
            return (Criteria) this;
        }

        public Criteria andPmStatusLessThanOrEqualTo(Integer value) {
            addCriterion("pm_status <=", value, "pmStatus");
            return (Criteria) this;
        }

        public Criteria andPmStatusIn(List<Integer> values) {
            addCriterion("pm_status in", values, "pmStatus");
            return (Criteria) this;
        }

        public Criteria andPmStatusNotIn(List<Integer> values) {
            addCriterion("pm_status not in", values, "pmStatus");
            return (Criteria) this;
        }

        public Criteria andPmStatusBetween(Integer value1, Integer value2) {
            addCriterion("pm_status between", value1, value2, "pmStatus");
            return (Criteria) this;
        }

        public Criteria andPmStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("pm_status not between", value1, value2, "pmStatus");
            return (Criteria) this;
        }

        public Criteria andPmReasonIsNull() {
            addCriterion("pm_reason is null");
            return (Criteria) this;
        }

        public Criteria andPmReasonIsNotNull() {
            addCriterion("pm_reason is not null");
            return (Criteria) this;
        }

        public Criteria andPmReasonEqualTo(String value) {
            addCriterion("pm_reason =", value, "pmReason");
            return (Criteria) this;
        }

        public Criteria andPmReasonNotEqualTo(String value) {
            addCriterion("pm_reason <>", value, "pmReason");
            return (Criteria) this;
        }

        public Criteria andPmReasonGreaterThan(String value) {
            addCriterion("pm_reason >", value, "pmReason");
            return (Criteria) this;
        }

        public Criteria andPmReasonGreaterThanOrEqualTo(String value) {
            addCriterion("pm_reason >=", value, "pmReason");
            return (Criteria) this;
        }

        public Criteria andPmReasonLessThan(String value) {
            addCriterion("pm_reason <", value, "pmReason");
            return (Criteria) this;
        }

        public Criteria andPmReasonLessThanOrEqualTo(String value) {
            addCriterion("pm_reason <=", value, "pmReason");
            return (Criteria) this;
        }

        public Criteria andPmReasonLike(String value) {
            addCriterion("pm_reason like", value, "pmReason");
            return (Criteria) this;
        }

        public Criteria andPmReasonNotLike(String value) {
            addCriterion("pm_reason not like", value, "pmReason");
            return (Criteria) this;
        }

        public Criteria andPmReasonIn(List<String> values) {
            addCriterion("pm_reason in", values, "pmReason");
            return (Criteria) this;
        }

        public Criteria andPmReasonNotIn(List<String> values) {
            addCriterion("pm_reason not in", values, "pmReason");
            return (Criteria) this;
        }

        public Criteria andPmReasonBetween(String value1, String value2) {
            addCriterion("pm_reason between", value1, value2, "pmReason");
            return (Criteria) this;
        }

        public Criteria andPmReasonNotBetween(String value1, String value2) {
            addCriterion("pm_reason not between", value1, value2, "pmReason");
            return (Criteria) this;
        }

        public Criteria andPmTimeIsNull() {
            addCriterion("pm_time is null");
            return (Criteria) this;
        }

        public Criteria andPmTimeIsNotNull() {
            addCriterion("pm_time is not null");
            return (Criteria) this;
        }

        public Criteria andPmTimeEqualTo(Date value) {
            addCriterionForJDBCDate("pm_time =", value, "pmTime");
            return (Criteria) this;
        }

        public Criteria andPmTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("pm_time <>", value, "pmTime");
            return (Criteria) this;
        }

        public Criteria andPmTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("pm_time >", value, "pmTime");
            return (Criteria) this;
        }

        public Criteria andPmTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("pm_time >=", value, "pmTime");
            return (Criteria) this;
        }

        public Criteria andPmTimeLessThan(Date value) {
            addCriterionForJDBCDate("pm_time <", value, "pmTime");
            return (Criteria) this;
        }

        public Criteria andPmTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("pm_time <=", value, "pmTime");
            return (Criteria) this;
        }

        public Criteria andPmTimeIn(List<Date> values) {
            addCriterionForJDBCDate("pm_time in", values, "pmTime");
            return (Criteria) this;
        }

        public Criteria andPmTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("pm_time not in", values, "pmTime");
            return (Criteria) this;
        }

        public Criteria andPmTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("pm_time between", value1, value2, "pmTime");
            return (Criteria) this;
        }

        public Criteria andPmTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("pm_time not between", value1, value2, "pmTime");
            return (Criteria) this;
        }

        public Criteria andProjectApplyNameIsNull() {
            addCriterion("project_apply_name is null");
            return (Criteria) this;
        }

        public Criteria andProjectApplyNameIsNotNull() {
            addCriterion("project_apply_name is not null");
            return (Criteria) this;
        }

        public Criteria andProjectApplyNameEqualTo(String value) {
            addCriterion("project_apply_name =", value, "projectApplyName");
            return (Criteria) this;
        }

        public Criteria andProjectApplyNameNotEqualTo(String value) {
            addCriterion("project_apply_name <>", value, "projectApplyName");
            return (Criteria) this;
        }

        public Criteria andProjectApplyNameGreaterThan(String value) {
            addCriterion("project_apply_name >", value, "projectApplyName");
            return (Criteria) this;
        }

        public Criteria andProjectApplyNameGreaterThanOrEqualTo(String value) {
            addCriterion("project_apply_name >=", value, "projectApplyName");
            return (Criteria) this;
        }

        public Criteria andProjectApplyNameLessThan(String value) {
            addCriterion("project_apply_name <", value, "projectApplyName");
            return (Criteria) this;
        }

        public Criteria andProjectApplyNameLessThanOrEqualTo(String value) {
            addCriterion("project_apply_name <=", value, "projectApplyName");
            return (Criteria) this;
        }

        public Criteria andProjectApplyNameLike(String value) {
            addCriterion("project_apply_name like", value, "projectApplyName");
            return (Criteria) this;
        }

        public Criteria andProjectApplyNameNotLike(String value) {
            addCriterion("project_apply_name not like", value, "projectApplyName");
            return (Criteria) this;
        }

        public Criteria andProjectApplyNameIn(List<String> values) {
            addCriterion("project_apply_name in", values, "projectApplyName");
            return (Criteria) this;
        }

        public Criteria andProjectApplyNameNotIn(List<String> values) {
            addCriterion("project_apply_name not in", values, "projectApplyName");
            return (Criteria) this;
        }

        public Criteria andProjectApplyNameBetween(String value1, String value2) {
            addCriterion("project_apply_name between", value1, value2, "projectApplyName");
            return (Criteria) this;
        }

        public Criteria andProjectApplyNameNotBetween(String value1, String value2) {
            addCriterion("project_apply_name not between", value1, value2, "projectApplyName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_members
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_members
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}