package mybatis.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table supply_borrow_record
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class SupplyBorrowRecord {
    /**
     * Database Column Remarks:
     *   外键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply_borrow_record.supply_id
     *
     * @mbggenerated
     */
    private Integer supplyId;

    /**
     * Database Column Remarks:
     *   借用人 外键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply_borrow_record.supply_borrow_account
     *
     * @mbggenerated
     */
    private String supplyBorrowAccount;

    /**
     * Database Column Remarks:
     *   借用日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply_borrow_record.supply_borrow_time
     *
     * @mbggenerated
     */
    private Date supplyBorrowTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply_borrow_record.supply_name
     *
     * @mbggenerated
     */
    private String supplyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply_borrow_record.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply_borrow_record.supply_id
     *
     * @return the value of supply_borrow_record.supply_id
     *
     * @mbggenerated
     */
    public Integer getSupplyId() {
        return supplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply_borrow_record.supply_id
     *
     * @param supplyId the value for supply_borrow_record.supply_id
     *
     * @mbggenerated
     */
    public void setSupplyId(Integer supplyId) {
        this.supplyId = supplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply_borrow_record.supply_borrow_account
     *
     * @return the value of supply_borrow_record.supply_borrow_account
     *
     * @mbggenerated
     */
    public String getSupplyBorrowAccount() {
        return supplyBorrowAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply_borrow_record.supply_borrow_account
     *
     * @param supplyBorrowAccount the value for supply_borrow_record.supply_borrow_account
     *
     * @mbggenerated
     */
    public void setSupplyBorrowAccount(String supplyBorrowAccount) {
        this.supplyBorrowAccount = supplyBorrowAccount == null ? null : supplyBorrowAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply_borrow_record.supply_borrow_time
     *
     * @return the value of supply_borrow_record.supply_borrow_time
     *
     * @mbggenerated
     */
    public Date getSupplyBorrowTime() {
        return supplyBorrowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply_borrow_record.supply_borrow_time
     *
     * @param supplyBorrowTime the value for supply_borrow_record.supply_borrow_time
     *
     * @mbggenerated
     */
    public void setSupplyBorrowTime(Date supplyBorrowTime) {
        this.supplyBorrowTime = supplyBorrowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply_borrow_record.supply_name
     *
     * @return the value of supply_borrow_record.supply_name
     *
     * @mbggenerated
     */
    public String getSupplyName() {
        return supplyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply_borrow_record.supply_name
     *
     * @param supplyName the value for supply_borrow_record.supply_name
     *
     * @mbggenerated
     */
    public void setSupplyName(String supplyName) {
        this.supplyName = supplyName == null ? null : supplyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply_borrow_record.user_name
     *
     * @return the value of supply_borrow_record.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply_borrow_record.user_name
     *
     * @param userName the value for supply_borrow_record.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }
}