package mybatis.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_activity
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class SysActivity {
    /**
     * Database Column Remarks:
     * 活动编号
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_activity.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     * 活动名
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_activity.activity_name
     *
     * @mbggenerated
     */
    private String activityName;

    /**
     * Database Column Remarks:
     * 活动地点
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_activity.activity_position
     *
     * @mbggenerated
     */
    private String activityPosition;

    /**
     * Database Column Remarks:
     * 申请人 外键
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_activity.activity_account
     *
     * @mbggenerated
     */
    private String activityAccount;

    /**
     * Database Column Remarks:
     * 活动开始时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_activity.activity_begin_time
     *
     * @mbggenerated
     */
    private Date activityBeginTime;

    /**
     * Database Column Remarks:
     * 活动结束时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_activity.activity_end_time
     *
     * @mbggenerated
     */
    private Date activityEndTime;

    /**
     * Database Column Remarks:
     * 活动预算
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_activity.activity_money
     *
     * @mbggenerated
     */
    private Double activityMoney;

    /**
     * Database Column Remarks:
     * 活动最多人数
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_activity.activity_min
     *
     * @mbggenerated
     */
    private Short activityMin;

    /**
     * Database Column Remarks:
     * 活动最少人数
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_activity.activity_max
     *
     * @mbggenerated
     */
    private Short activityMax;

    /**
     * Database Column Remarks:
     * 申请状态 0待审核/1成功/-1不成功/2已结束
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_activity.activity_status
     *
     * @mbggenerated
     */
    private Short activityStatus = 0;

    /**
     * Database Column Remarks:
     * 活动申请人姓名
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_activity.activity_user_name
     *
     * @mbggenerated
     */
    private String activityUserName;

    /**
     * Database Column Remarks:
     * 申请说明
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_activity.activity_remark
     *
     * @mbggenerated
     */
    private String activityRemark;

    /**
     * 当前报名人数
     */
    private Integer activityCur = 0;

    private String beginTimeStr;

    private String endTimeStr;

    public String getBeginTimeStr() {
        return beginTimeStr;
    }

    public void setBeginTimeStr(String beginTimeStr) {
        this.beginTimeStr = beginTimeStr;
    }

    public String getEndTimeStr() {
        return endTimeStr;
    }

    public void setEndTimeStr(String endTimeStr) {
        this.endTimeStr = endTimeStr;
    }

    public Integer getActivityCur() {
        return activityCur;
    }

    public void setActivityCur(Integer activityCur) {
        this.activityCur = activityCur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_activity.id
     *
     * @return the value of sys_activity.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_activity.id
     *
     * @param id the value for sys_activity.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_activity.activity_name
     *
     * @return the value of sys_activity.activity_name
     * @mbggenerated
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_activity.activity_name
     *
     * @param activityName the value for sys_activity.activity_name
     * @mbggenerated
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_activity.activity_position
     *
     * @return the value of sys_activity.activity_position
     * @mbggenerated
     */
    public String getActivityPosition() {
        return activityPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_activity.activity_position
     *
     * @param activityPosition the value for sys_activity.activity_position
     * @mbggenerated
     */
    public void setActivityPosition(String activityPosition) {
        this.activityPosition = activityPosition == null ? null : activityPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_activity.activity_account
     *
     * @return the value of sys_activity.activity_account
     * @mbggenerated
     */
    public String getActivityAccount() {
        return activityAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_activity.activity_account
     *
     * @param activityAccount the value for sys_activity.activity_account
     * @mbggenerated
     */
    public void setActivityAccount(String activityAccount) {
        this.activityAccount = activityAccount == null ? null : activityAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_activity.activity_begin_time
     *
     * @return the value of sys_activity.activity_begin_time
     * @mbggenerated
     */
    public Date getActivityBeginTime() {
        return activityBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_activity.activity_begin_time
     *
     * @param activityBeginTime the value for sys_activity.activity_begin_time
     * @mbggenerated
     */
    public void setActivityBeginTime(Date activityBeginTime) {
        this.activityBeginTime = activityBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_activity.activity_end_time
     *
     * @return the value of sys_activity.activity_end_time
     * @mbggenerated
     */
    public Date getActivityEndTime() {
        return activityEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_activity.activity_end_time
     *
     * @param activityEndTime the value for sys_activity.activity_end_time
     * @mbggenerated
     */
    public void setActivityEndTime(Date activityEndTime) {
        this.activityEndTime = activityEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_activity.activity_money
     *
     * @return the value of sys_activity.activity_money
     * @mbggenerated
     */
    public Double getActivityMoney() {
        return activityMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_activity.activity_money
     *
     * @param activityMoney the value for sys_activity.activity_money
     * @mbggenerated
     */
    public void setActivityMoney(Double activityMoney) {
        this.activityMoney = activityMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_activity.activity_min
     *
     * @return the value of sys_activity.activity_min
     * @mbggenerated
     */
    public Short getActivityMin() {
        return activityMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_activity.activity_min
     *
     * @param activityMin the value for sys_activity.activity_min
     * @mbggenerated
     */
    public void setActivityMin(Short activityMin) {
        this.activityMin = activityMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_activity.activity_max
     *
     * @return the value of sys_activity.activity_max
     * @mbggenerated
     */
    public Short getActivityMax() {
        return activityMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_activity.activity_max
     *
     * @param activityMax the value for sys_activity.activity_max
     * @mbggenerated
     */
    public void setActivityMax(Short activityMax) {
        this.activityMax = activityMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_activity.activity_status
     *
     * @return the value of sys_activity.activity_status
     * @mbggenerated
     */
    public Short getActivityStatus() {
        return activityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_activity.activity_status
     *
     * @param activityStatus the value for sys_activity.activity_status
     * @mbggenerated
     */
    public void setActivityStatus(Short activityStatus) {
        this.activityStatus = activityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_activity.activity_user_name
     *
     * @return the value of sys_activity.activity_user_name
     * @mbggenerated
     */
    public String getActivityUserName() {
        return activityUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_activity.activity_user_name
     *
     * @param activityUserName the value for sys_activity.activity_user_name
     * @mbggenerated
     */
    public void setActivityUserName(String activityUserName) {
        this.activityUserName = activityUserName == null ? null : activityUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_activity.activity_remark
     *
     * @return the value of sys_activity.activity_remark
     * @mbggenerated
     */
    public String getActivityRemark() {
        return activityRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_activity.activity_remark
     *
     * @param activityRemark the value for sys_activity.activity_remark
     * @mbggenerated
     */
    public void setActivityRemark(String activityRemark) {
        this.activityRemark = activityRemark == null ? null : activityRemark.trim();
    }
}