package mybatis.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_announcement
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class SysAnnouncement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_announcement.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   发布日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_announcement.an_date
     *
     * @mbggenerated
     */
    private Date anDate;

    /**
     * Database Column Remarks:
     *   发布人账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_announcement.an_account
     *
     * @mbggenerated
     */
    private String anAccount;

    /**
     * Database Column Remarks:
     *   发布人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_announcement.an_name
     *
     * @mbggenerated
     */
    private String anName;

    /**
     * Database Column Remarks:
     *   通知内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_announcement.an_text
     *
     * @mbggenerated
     */
    private String anText;

    public String anDateStr;

    public String getAnDateStr() {
        return anDateStr;
    }

    public void setAnDateStr(String anDateStr) {
        this.anDateStr = anDateStr;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_announcement.id
     *
     * @return the value of sys_announcement.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_announcement.id
     *
     * @param id the value for sys_announcement.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_announcement.an_date
     *
     * @return the value of sys_announcement.an_date
     *
     * @mbggenerated
     */
    public Date getAnDate() {
        return anDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_announcement.an_date
     *
     * @param anDate the value for sys_announcement.an_date
     *
     * @mbggenerated
     */
    public void setAnDate(Date anDate) {
        this.anDate = anDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_announcement.an_account
     *
     * @return the value of sys_announcement.an_account
     *
     * @mbggenerated
     */
    public String getAnAccount() {
        return anAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_announcement.an_account
     *
     * @param anAccount the value for sys_announcement.an_account
     *
     * @mbggenerated
     */
    public void setAnAccount(String anAccount) {
        this.anAccount = anAccount == null ? null : anAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_announcement.an_name
     *
     * @return the value of sys_announcement.an_name
     *
     * @mbggenerated
     */
    public String getAnName() {
        return anName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_announcement.an_name
     *
     * @param anName the value for sys_announcement.an_name
     *
     * @mbggenerated
     */
    public void setAnName(String anName) {
        this.anName = anName == null ? null : anName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_announcement.an_text
     *
     * @return the value of sys_announcement.an_text
     *
     * @mbggenerated
     */
    public String getAnText() {
        return anText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_announcement.an_text
     *
     * @param anText the value for sys_announcement.an_text
     *
     * @mbggenerated
     */
    public void setAnText(String anText) {
        this.anText = anText == null ? null : anText.trim();
    }
}