package mybatis.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_book
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class SysBook {
    @Override
	public String toString() {
		return "SysBook [id=" + id + ", bookIsbn=" + bookIsbn + ", bookName=" + bookName + ", bookWriter=" + bookWriter
				+ ", bookPub=" + bookPub + ", bookStatus=" + bookStatus + ", bookBuyer=" + bookBuyer + ", bookMark="
				+ bookMark + ", bookBorrower=" + bookBorrower + ", bookBorrowTime=" + bookBorrowTime + "]\n";
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_book.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_book.book_isbn
     *
     * @mbggenerated
     */
    private String bookIsbn;

    /**
     * Database Column Remarks:
     *   书名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_book.book_name
     *
     * @mbggenerated
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_book.book_writer
     *
     * @mbggenerated
     */
    private String bookWriter;

    /**
     * Database Column Remarks:
     *   出版社
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_book.book_pub
     *
     * @mbggenerated
     */
    private String bookPub;

    /**
     * Database Column Remarks:
     *   状态 1还在/0借出/-3申请/-2失败/1成功
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_book.book_status
     *
     * @mbggenerated
     */
    private Byte bookStatus;

    /**
     * Database Column Remarks:
     *   购买人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_book.book_buyer
     *
     * @mbggenerated
     */
    private String bookBuyer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_book.book_mark
     *
     * @mbggenerated
     */
    private String bookMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_book.book_borrower
     *
     * @mbggenerated
     */
    private String bookBorrower;

    /**
     * Database Column Remarks:
     *   借用时间（原来是购买时间，但是没用了）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_book.book_borrow_time
     *
     * @mbggenerated
     */
    private Date bookBorrowTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_book.id
     *
     * @return the value of sys_book.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_book.id
     *
     * @param id the value for sys_book.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_book.book_isbn
     *
     * @return the value of sys_book.book_isbn
     *
     * @mbggenerated
     */
    public String getBookIsbn() {
        return bookIsbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_book.book_isbn
     *
     * @param bookIsbn the value for sys_book.book_isbn
     *
     * @mbggenerated
     */
    public void setBookIsbn(String bookIsbn) {
        this.bookIsbn = bookIsbn == null ? null : bookIsbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_book.book_name
     *
     * @return the value of sys_book.book_name
     *
     * @mbggenerated
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_book.book_name
     *
     * @param bookName the value for sys_book.book_name
     *
     * @mbggenerated
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_book.book_writer
     *
     * @return the value of sys_book.book_writer
     *
     * @mbggenerated
     */
    public String getBookWriter() {
        return bookWriter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_book.book_writer
     *
     * @param bookWriter the value for sys_book.book_writer
     *
     * @mbggenerated
     */
    public void setBookWriter(String bookWriter) {
        this.bookWriter = bookWriter == null ? null : bookWriter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_book.book_pub
     *
     * @return the value of sys_book.book_pub
     *
     * @mbggenerated
     */
    public String getBookPub() {
        return bookPub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_book.book_pub
     *
     * @param bookPub the value for sys_book.book_pub
     *
     * @mbggenerated
     */
    public void setBookPub(String bookPub) {
        this.bookPub = bookPub == null ? null : bookPub.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_book.book_status
     *
     * @return the value of sys_book.book_status
     *
     * @mbggenerated
     */
    public Byte getBookStatus() {
        return bookStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_book.book_status
     *
     * @param bookStatus the value for sys_book.book_status
     *
     * @mbggenerated
     */
    public void setBookStatus(Byte bookStatus) {
        this.bookStatus = bookStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_book.book_buyer
     *
     * @return the value of sys_book.book_buyer
     *
     * @mbggenerated
     */
    public String getBookBuyer() {
        return bookBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_book.book_buyer
     *
     * @param bookBuyer the value for sys_book.book_buyer
     *
     * @mbggenerated
     */
    public void setBookBuyer(String bookBuyer) {
        this.bookBuyer = bookBuyer == null ? null : bookBuyer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_book.book_mark
     *
     * @return the value of sys_book.book_mark
     *
     * @mbggenerated
     */
    public String getBookMark() {
        return bookMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_book.book_mark
     *
     * @param bookMark the value for sys_book.book_mark
     *
     * @mbggenerated
     */
    public void setBookMark(String bookMark) {
        this.bookMark = bookMark == null ? null : bookMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_book.book_borrower
     *
     * @return the value of sys_book.book_borrower
     *
     * @mbggenerated
     */
    public String getBookBorrower() {
        return bookBorrower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_book.book_borrower
     *
     * @param bookBorrower the value for sys_book.book_borrower
     *
     * @mbggenerated
     */
    public void setBookBorrower(String bookBorrower) {
        this.bookBorrower = bookBorrower == null ? null : bookBorrower.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_book.book_borrow_time
     *
     * @return the value of sys_book.book_borrow_time
     *
     * @mbggenerated
     */
    public Date getBookBorrowTime() {
        return bookBorrowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_book.book_borrow_time
     *
     * @param bookBorrowTime the value for sys_book.book_borrow_time
     *
     * @mbggenerated
     */
    public void setBookBorrowTime(Date bookBorrowTime) {
        this.bookBorrowTime = bookBorrowTime;
    }
}