package mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysBookExample {
    private int start;//设置分页开始

    private int limit;//设置分页的每页的数量</strong>

    public int getStart() {
        return start;
    }

    public void setStart(int start) {
        this.start = start;
    }

    public int getLimit() {
        return limit;
    }

    public void setLimit(int limit) {
        this.limit = limit;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    public SysBookExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBookIsbnIsNull() {
            addCriterion("book_isbn is null");
            return (Criteria) this;
        }

        public Criteria andBookIsbnIsNotNull() {
            addCriterion("book_isbn is not null");
            return (Criteria) this;
        }

        public Criteria andBookIsbnEqualTo(String value) {
            addCriterion("book_isbn =", value, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnNotEqualTo(String value) {
            addCriterion("book_isbn <>", value, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnGreaterThan(String value) {
            addCriterion("book_isbn >", value, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnGreaterThanOrEqualTo(String value) {
            addCriterion("book_isbn >=", value, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnLessThan(String value) {
            addCriterion("book_isbn <", value, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnLessThanOrEqualTo(String value) {
            addCriterion("book_isbn <=", value, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnLike(String value) {
            addCriterion("book_isbn like", value, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnNotLike(String value) {
            addCriterion("book_isbn not like", value, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnIn(List<String> values) {
            addCriterion("book_isbn in", values, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnNotIn(List<String> values) {
            addCriterion("book_isbn not in", values, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnBetween(String value1, String value2) {
            addCriterion("book_isbn between", value1, value2, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnNotBetween(String value1, String value2) {
            addCriterion("book_isbn not between", value1, value2, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookNameIsNull() {
            addCriterion("book_name is null");
            return (Criteria) this;
        }

        public Criteria andBookNameIsNotNull() {
            addCriterion("book_name is not null");
            return (Criteria) this;
        }

        public Criteria andBookNameEqualTo(String value) {
            addCriterion("book_name =", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameNotEqualTo(String value) {
            addCriterion("book_name <>", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameGreaterThan(String value) {
            addCriterion("book_name >", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameGreaterThanOrEqualTo(String value) {
            addCriterion("book_name >=", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameLessThan(String value) {
            addCriterion("book_name <", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameLessThanOrEqualTo(String value) {
            addCriterion("book_name <=", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameLike(String value) {
            addCriterion("book_name like", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameNotLike(String value) {
            addCriterion("book_name not like", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameIn(List<String> values) {
            addCriterion("book_name in", values, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameNotIn(List<String> values) {
            addCriterion("book_name not in", values, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameBetween(String value1, String value2) {
            addCriterion("book_name between", value1, value2, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameNotBetween(String value1, String value2) {
            addCriterion("book_name not between", value1, value2, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookWriterIsNull() {
            addCriterion("book_writer is null");
            return (Criteria) this;
        }

        public Criteria andBookWriterIsNotNull() {
            addCriterion("book_writer is not null");
            return (Criteria) this;
        }

        public Criteria andBookWriterEqualTo(String value) {
            addCriterion("book_writer =", value, "bookWriter");
            return (Criteria) this;
        }

        public Criteria andBookWriterNotEqualTo(String value) {
            addCriterion("book_writer <>", value, "bookWriter");
            return (Criteria) this;
        }

        public Criteria andBookWriterGreaterThan(String value) {
            addCriterion("book_writer >", value, "bookWriter");
            return (Criteria) this;
        }

        public Criteria andBookWriterGreaterThanOrEqualTo(String value) {
            addCriterion("book_writer >=", value, "bookWriter");
            return (Criteria) this;
        }

        public Criteria andBookWriterLessThan(String value) {
            addCriterion("book_writer <", value, "bookWriter");
            return (Criteria) this;
        }

        public Criteria andBookWriterLessThanOrEqualTo(String value) {
            addCriterion("book_writer <=", value, "bookWriter");
            return (Criteria) this;
        }

        public Criteria andBookWriterLike(String value) {
            addCriterion("book_writer like", value, "bookWriter");
            return (Criteria) this;
        }

        public Criteria andBookWriterNotLike(String value) {
            addCriterion("book_writer not like", value, "bookWriter");
            return (Criteria) this;
        }

        public Criteria andBookWriterIn(List<String> values) {
            addCriterion("book_writer in", values, "bookWriter");
            return (Criteria) this;
        }

        public Criteria andBookWriterNotIn(List<String> values) {
            addCriterion("book_writer not in", values, "bookWriter");
            return (Criteria) this;
        }

        public Criteria andBookWriterBetween(String value1, String value2) {
            addCriterion("book_writer between", value1, value2, "bookWriter");
            return (Criteria) this;
        }

        public Criteria andBookWriterNotBetween(String value1, String value2) {
            addCriterion("book_writer not between", value1, value2, "bookWriter");
            return (Criteria) this;
        }

        public Criteria andBookPubIsNull() {
            addCriterion("book_pub is null");
            return (Criteria) this;
        }

        public Criteria andBookPubIsNotNull() {
            addCriterion("book_pub is not null");
            return (Criteria) this;
        }

        public Criteria andBookPubEqualTo(String value) {
            addCriterion("book_pub =", value, "bookPub");
            return (Criteria) this;
        }

        public Criteria andBookPubNotEqualTo(String value) {
            addCriterion("book_pub <>", value, "bookPub");
            return (Criteria) this;
        }

        public Criteria andBookPubGreaterThan(String value) {
            addCriterion("book_pub >", value, "bookPub");
            return (Criteria) this;
        }

        public Criteria andBookPubGreaterThanOrEqualTo(String value) {
            addCriterion("book_pub >=", value, "bookPub");
            return (Criteria) this;
        }

        public Criteria andBookPubLessThan(String value) {
            addCriterion("book_pub <", value, "bookPub");
            return (Criteria) this;
        }

        public Criteria andBookPubLessThanOrEqualTo(String value) {
            addCriterion("book_pub <=", value, "bookPub");
            return (Criteria) this;
        }

        public Criteria andBookPubLike(String value) {
            addCriterion("book_pub like", value, "bookPub");
            return (Criteria) this;
        }

        public Criteria andBookPubNotLike(String value) {
            addCriterion("book_pub not like", value, "bookPub");
            return (Criteria) this;
        }

        public Criteria andBookPubIn(List<String> values) {
            addCriterion("book_pub in", values, "bookPub");
            return (Criteria) this;
        }

        public Criteria andBookPubNotIn(List<String> values) {
            addCriterion("book_pub not in", values, "bookPub");
            return (Criteria) this;
        }

        public Criteria andBookPubBetween(String value1, String value2) {
            addCriterion("book_pub between", value1, value2, "bookPub");
            return (Criteria) this;
        }

        public Criteria andBookPubNotBetween(String value1, String value2) {
            addCriterion("book_pub not between", value1, value2, "bookPub");
            return (Criteria) this;
        }

        public Criteria andBookStatusIsNull() {
            addCriterion("book_status is null");
            return (Criteria) this;
        }

        public Criteria andBookStatusIsNotNull() {
            addCriterion("book_status is not null");
            return (Criteria) this;
        }

        public Criteria andBookStatusEqualTo(Byte value) {
            addCriterion("book_status =", value, "bookStatus");
            return (Criteria) this;
        }

        public Criteria andBookStatusNotEqualTo(Byte value) {
            addCriterion("book_status <>", value, "bookStatus");
            return (Criteria) this;
        }

        public Criteria andBookStatusGreaterThan(Byte value) {
            addCriterion("book_status >", value, "bookStatus");
            return (Criteria) this;
        }

        public Criteria andBookStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("book_status >=", value, "bookStatus");
            return (Criteria) this;
        }

        public Criteria andBookStatusLessThan(Byte value) {
            addCriterion("book_status <", value, "bookStatus");
            return (Criteria) this;
        }

        public Criteria andBookStatusLessThanOrEqualTo(Byte value) {
            addCriterion("book_status <=", value, "bookStatus");
            return (Criteria) this;
        }

        public Criteria andBookStatusIn(List<Byte> values) {
            addCriterion("book_status in", values, "bookStatus");
            return (Criteria) this;
        }

        public Criteria andBookStatusNotIn(List<Byte> values) {
            addCriterion("book_status not in", values, "bookStatus");
            return (Criteria) this;
        }

        public Criteria andBookStatusBetween(Byte value1, Byte value2) {
            addCriterion("book_status between", value1, value2, "bookStatus");
            return (Criteria) this;
        }

        public Criteria andBookStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("book_status not between", value1, value2, "bookStatus");
            return (Criteria) this;
        }

        public Criteria andBookBuyerIsNull() {
            addCriterion("book_buyer is null");
            return (Criteria) this;
        }

        public Criteria andBookBuyerIsNotNull() {
            addCriterion("book_buyer is not null");
            return (Criteria) this;
        }

        public Criteria andBookBuyerEqualTo(String value) {
            addCriterion("book_buyer =", value, "bookBuyer");
            return (Criteria) this;
        }

        public Criteria andBookBuyerNotEqualTo(String value) {
            addCriterion("book_buyer <>", value, "bookBuyer");
            return (Criteria) this;
        }

        public Criteria andBookBuyerGreaterThan(String value) {
            addCriterion("book_buyer >", value, "bookBuyer");
            return (Criteria) this;
        }

        public Criteria andBookBuyerGreaterThanOrEqualTo(String value) {
            addCriterion("book_buyer >=", value, "bookBuyer");
            return (Criteria) this;
        }

        public Criteria andBookBuyerLessThan(String value) {
            addCriterion("book_buyer <", value, "bookBuyer");
            return (Criteria) this;
        }

        public Criteria andBookBuyerLessThanOrEqualTo(String value) {
            addCriterion("book_buyer <=", value, "bookBuyer");
            return (Criteria) this;
        }

        public Criteria andBookBuyerLike(String value) {
            addCriterion("book_buyer like", value, "bookBuyer");
            return (Criteria) this;
        }

        public Criteria andBookBuyerNotLike(String value) {
            addCriterion("book_buyer not like", value, "bookBuyer");
            return (Criteria) this;
        }

        public Criteria andBookBuyerIn(List<String> values) {
            addCriterion("book_buyer in", values, "bookBuyer");
            return (Criteria) this;
        }

        public Criteria andBookBuyerNotIn(List<String> values) {
            addCriterion("book_buyer not in", values, "bookBuyer");
            return (Criteria) this;
        }

        public Criteria andBookBuyerBetween(String value1, String value2) {
            addCriterion("book_buyer between", value1, value2, "bookBuyer");
            return (Criteria) this;
        }

        public Criteria andBookBuyerNotBetween(String value1, String value2) {
            addCriterion("book_buyer not between", value1, value2, "bookBuyer");
            return (Criteria) this;
        }

        public Criteria andBookMarkIsNull() {
            addCriterion("book_mark is null");
            return (Criteria) this;
        }

        public Criteria andBookMarkIsNotNull() {
            addCriterion("book_mark is not null");
            return (Criteria) this;
        }

        public Criteria andBookMarkEqualTo(String value) {
            addCriterion("book_mark =", value, "bookMark");
            return (Criteria) this;
        }

        public Criteria andBookMarkNotEqualTo(String value) {
            addCriterion("book_mark <>", value, "bookMark");
            return (Criteria) this;
        }

        public Criteria andBookMarkGreaterThan(String value) {
            addCriterion("book_mark >", value, "bookMark");
            return (Criteria) this;
        }

        public Criteria andBookMarkGreaterThanOrEqualTo(String value) {
            addCriterion("book_mark >=", value, "bookMark");
            return (Criteria) this;
        }

        public Criteria andBookMarkLessThan(String value) {
            addCriterion("book_mark <", value, "bookMark");
            return (Criteria) this;
        }

        public Criteria andBookMarkLessThanOrEqualTo(String value) {
            addCriterion("book_mark <=", value, "bookMark");
            return (Criteria) this;
        }

        public Criteria andBookMarkLike(String value) {
            addCriterion("book_mark like", value, "bookMark");
            return (Criteria) this;
        }

        public Criteria andBookMarkNotLike(String value) {
            addCriterion("book_mark not like", value, "bookMark");
            return (Criteria) this;
        }

        public Criteria andBookMarkIn(List<String> values) {
            addCriterion("book_mark in", values, "bookMark");
            return (Criteria) this;
        }

        public Criteria andBookMarkNotIn(List<String> values) {
            addCriterion("book_mark not in", values, "bookMark");
            return (Criteria) this;
        }

        public Criteria andBookMarkBetween(String value1, String value2) {
            addCriterion("book_mark between", value1, value2, "bookMark");
            return (Criteria) this;
        }

        public Criteria andBookMarkNotBetween(String value1, String value2) {
            addCriterion("book_mark not between", value1, value2, "bookMark");
            return (Criteria) this;
        }

        public Criteria andBookBorrowerIsNull() {
            addCriterion("book_borrower is null");
            return (Criteria) this;
        }

        public Criteria andBookBorrowerIsNotNull() {
            addCriterion("book_borrower is not null");
            return (Criteria) this;
        }

        public Criteria andBookBorrowerEqualTo(String value) {
            addCriterion("book_borrower =", value, "bookBorrower");
            return (Criteria) this;
        }

        public Criteria andBookBorrowerNotEqualTo(String value) {
            addCriterion("book_borrower <>", value, "bookBorrower");
            return (Criteria) this;
        }

        public Criteria andBookBorrowerGreaterThan(String value) {
            addCriterion("book_borrower >", value, "bookBorrower");
            return (Criteria) this;
        }

        public Criteria andBookBorrowerGreaterThanOrEqualTo(String value) {
            addCriterion("book_borrower >=", value, "bookBorrower");
            return (Criteria) this;
        }

        public Criteria andBookBorrowerLessThan(String value) {
            addCriterion("book_borrower <", value, "bookBorrower");
            return (Criteria) this;
        }

        public Criteria andBookBorrowerLessThanOrEqualTo(String value) {
            addCriterion("book_borrower <=", value, "bookBorrower");
            return (Criteria) this;
        }

        public Criteria andBookBorrowerLike(String value) {
            addCriterion("book_borrower like", value, "bookBorrower");
            return (Criteria) this;
        }

        public Criteria andBookBorrowerNotLike(String value) {
            addCriterion("book_borrower not like", value, "bookBorrower");
            return (Criteria) this;
        }

        public Criteria andBookBorrowerIn(List<String> values) {
            addCriterion("book_borrower in", values, "bookBorrower");
            return (Criteria) this;
        }

        public Criteria andBookBorrowerNotIn(List<String> values) {
            addCriterion("book_borrower not in", values, "bookBorrower");
            return (Criteria) this;
        }

        public Criteria andBookBorrowerBetween(String value1, String value2) {
            addCriterion("book_borrower between", value1, value2, "bookBorrower");
            return (Criteria) this;
        }

        public Criteria andBookBorrowerNotBetween(String value1, String value2) {
            addCriterion("book_borrower not between", value1, value2, "bookBorrower");
            return (Criteria) this;
        }

        public Criteria andBookBorrowTimeIsNull() {
            addCriterion("book_borrow_time is null");
            return (Criteria) this;
        }

        public Criteria andBookBorrowTimeIsNotNull() {
            addCriterion("book_borrow_time is not null");
            return (Criteria) this;
        }

        public Criteria andBookBorrowTimeEqualTo(Date value) {
            addCriterion("book_borrow_time =", value, "bookBorrowTime");
            return (Criteria) this;
        }

        public Criteria andBookBorrowTimeNotEqualTo(Date value) {
            addCriterion("book_borrow_time <>", value, "bookBorrowTime");
            return (Criteria) this;
        }

        public Criteria andBookBorrowTimeGreaterThan(Date value) {
            addCriterion("book_borrow_time >", value, "bookBorrowTime");
            return (Criteria) this;
        }

        public Criteria andBookBorrowTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("book_borrow_time >=", value, "bookBorrowTime");
            return (Criteria) this;
        }

        public Criteria andBookBorrowTimeLessThan(Date value) {
            addCriterion("book_borrow_time <", value, "bookBorrowTime");
            return (Criteria) this;
        }

        public Criteria andBookBorrowTimeLessThanOrEqualTo(Date value) {
            addCriterion("book_borrow_time <=", value, "bookBorrowTime");
            return (Criteria) this;
        }

        public Criteria andBookBorrowTimeIn(List<Date> values) {
            addCriterion("book_borrow_time in", values, "bookBorrowTime");
            return (Criteria) this;
        }

        public Criteria andBookBorrowTimeNotIn(List<Date> values) {
            addCriterion("book_borrow_time not in", values, "bookBorrowTime");
            return (Criteria) this;
        }

        public Criteria andBookBorrowTimeBetween(Date value1, Date value2) {
            addCriterion("book_borrow_time between", value1, value2, "bookBorrowTime");
            return (Criteria) this;
        }

        public Criteria andBookBorrowTimeNotBetween(Date value1, Date value2) {
            addCriterion("book_borrow_time not between", value1, value2, "bookBorrowTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_book
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_book
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}