package mybatis.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_health_head
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class SysHealthHead {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_health_head.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   第几周
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_health_head.health_week_order
     *
     * @mbggenerated
     */
    private Integer healthWeekOrder;

    /**
     * Database Column Remarks:
     *   负责人账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_health_head.health_account
     *
     * @mbggenerated
     */
    private String healthAccount;

    /**
     * Database Column Remarks:
     *   负责人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_health_head.health_name
     *
     * @mbggenerated
     */
    private String healthName;

    /**
     * Database Column Remarks:
     *   负责人2账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_health_head.health_account2
     *
     * @mbggenerated
     */
    private String healthAccount2;

    /**
     * Database Column Remarks:
     *   负责人2姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_health_head.health_name2
     *
     * @mbggenerated
     */
    private String healthName2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_health_head.id
     *
     * @return the value of sys_health_head.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_health_head.id
     *
     * @param id the value for sys_health_head.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_health_head.health_week_order
     *
     * @return the value of sys_health_head.health_week_order
     *
     * @mbggenerated
     */
    public Integer getHealthWeekOrder() {
        return healthWeekOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_health_head.health_week_order
     *
     * @param healthWeekOrder the value for sys_health_head.health_week_order
     *
     * @mbggenerated
     */
    public void setHealthWeekOrder(Integer healthWeekOrder) {
        this.healthWeekOrder = healthWeekOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_health_head.health_account
     *
     * @return the value of sys_health_head.health_account
     *
     * @mbggenerated
     */
    public String getHealthAccount() {
        return healthAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_health_head.health_account
     *
     * @param healthAccount the value for sys_health_head.health_account
     *
     * @mbggenerated
     */
    public void setHealthAccount(String healthAccount) {
        this.healthAccount = healthAccount == null ? null : healthAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_health_head.health_name
     *
     * @return the value of sys_health_head.health_name
     *
     * @mbggenerated
     */
    public String getHealthName() {
        return healthName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_health_head.health_name
     *
     * @param healthName the value for sys_health_head.health_name
     *
     * @mbggenerated
     */
    public void setHealthName(String healthName) {
        this.healthName = healthName == null ? null : healthName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_health_head.health_account2
     *
     * @return the value of sys_health_head.health_account2
     *
     * @mbggenerated
     */
    public String getHealthAccount2() {
        return healthAccount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_health_head.health_account2
     *
     * @param healthAccount2 the value for sys_health_head.health_account2
     *
     * @mbggenerated
     */
    public void setHealthAccount2(String healthAccount2) {
        this.healthAccount2 = healthAccount2 == null ? null : healthAccount2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_health_head.health_name2
     *
     * @return the value of sys_health_head.health_name2
     *
     * @mbggenerated
     */
    public String getHealthName2() {
        return healthName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_health_head.health_name2
     *
     * @param healthName2 the value for sys_health_head.health_name2
     *
     * @mbggenerated
     */
    public void setHealthName2(String healthName2) {
        this.healthName2 = healthName2 == null ? null : healthName2.trim();
    }
}