package mybatis.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_health_head_date
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class SysHealthHeadDate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_health_head_date.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   卫生负责人文件上传日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_health_head_date.health_head_date
     *
     * @mbggenerated
     */
    private Date healthHeadDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_health_head_date.id
     *
     * @return the value of sys_health_head_date.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_health_head_date.id
     *
     * @param id the value for sys_health_head_date.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_health_head_date.health_head_date
     *
     * @return the value of sys_health_head_date.health_head_date
     *
     * @mbggenerated
     */
    public Date getHealthHeadDate() {
        return healthHeadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_health_head_date.health_head_date
     *
     * @param healthHeadDate the value for sys_health_head_date.health_head_date
     *
     * @mbggenerated
     */
    public void setHealthHeadDate(Date healthHeadDate) {
        this.healthHeadDate = healthHeadDate;
    }
}