package mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysSupplyExample {
	private int start;//开始
	
	private int limit;//页数
	
    public int getStart() {
		return start;
	}
 
	public void setStart(int start) {
		this.start = start;
	}
 
	public int getLimit() {
		return limit;
	}
 
	public void setLimit(int limit) {
		this.limit = limit;
	}
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_supply
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_supply
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_supply
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_supply
     *
     * @mbggenerated
     */
    public SysSupplyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_supply
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_supply
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_supply
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_supply
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_supply
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_supply
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_supply
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_supply
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_supply
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_supply
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_supply
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSupplyNameIsNull() {
            addCriterion("supply_name is null");
            return (Criteria) this;
        }

        public Criteria andSupplyNameIsNotNull() {
            addCriterion("supply_name is not null");
            return (Criteria) this;
        }

        public Criteria andSupplyNameEqualTo(String value) {
            addCriterion("supply_name =", value, "supplyName");
            return (Criteria) this;
        }

        public Criteria andSupplyNameNotEqualTo(String value) {
            addCriterion("supply_name <>", value, "supplyName");
            return (Criteria) this;
        }

        public Criteria andSupplyNameGreaterThan(String value) {
            addCriterion("supply_name >", value, "supplyName");
            return (Criteria) this;
        }

        public Criteria andSupplyNameGreaterThanOrEqualTo(String value) {
            addCriterion("supply_name >=", value, "supplyName");
            return (Criteria) this;
        }

        public Criteria andSupplyNameLessThan(String value) {
            addCriterion("supply_name <", value, "supplyName");
            return (Criteria) this;
        }

        public Criteria andSupplyNameLessThanOrEqualTo(String value) {
            addCriterion("supply_name <=", value, "supplyName");
            return (Criteria) this;
        }

        public Criteria andSupplyNameLike(String value) {
            addCriterion("supply_name like", value, "supplyName");
            return (Criteria) this;
        }

        public Criteria andSupplyNameNotLike(String value) {
            addCriterion("supply_name not like", value, "supplyName");
            return (Criteria) this;
        }

        public Criteria andSupplyNameIn(List<String> values) {
            addCriterion("supply_name in", values, "supplyName");
            return (Criteria) this;
        }

        public Criteria andSupplyNameNotIn(List<String> values) {
            addCriterion("supply_name not in", values, "supplyName");
            return (Criteria) this;
        }

        public Criteria andSupplyNameBetween(String value1, String value2) {
            addCriterion("supply_name between", value1, value2, "supplyName");
            return (Criteria) this;
        }

        public Criteria andSupplyNameNotBetween(String value1, String value2) {
            addCriterion("supply_name not between", value1, value2, "supplyName");
            return (Criteria) this;
        }

        public Criteria andSupplyNumberIsNull() {
            addCriterion("supply_number is null");
            return (Criteria) this;
        }

        public Criteria andSupplyNumberIsNotNull() {
            addCriterion("supply_number is not null");
            return (Criteria) this;
        }

        public Criteria andSupplyNumberEqualTo(String value) {
            addCriterion("supply_number =", value, "supplyNumber");
            return (Criteria) this;
        }

        public Criteria andSupplyNumberNotEqualTo(String value) {
            addCriterion("supply_number <>", value, "supplyNumber");
            return (Criteria) this;
        }

        public Criteria andSupplyNumberGreaterThan(String value) {
            addCriterion("supply_number >", value, "supplyNumber");
            return (Criteria) this;
        }

        public Criteria andSupplyNumberGreaterThanOrEqualTo(String value) {
            addCriterion("supply_number >=", value, "supplyNumber");
            return (Criteria) this;
        }

        public Criteria andSupplyNumberLessThan(String value) {
            addCriterion("supply_number <", value, "supplyNumber");
            return (Criteria) this;
        }

        public Criteria andSupplyNumberLessThanOrEqualTo(String value) {
            addCriterion("supply_number <=", value, "supplyNumber");
            return (Criteria) this;
        }

        public Criteria andSupplyNumberLike(String value) {
            addCriterion("supply_number like", value, "supplyNumber");
            return (Criteria) this;
        }

        public Criteria andSupplyNumberNotLike(String value) {
            addCriterion("supply_number not like", value, "supplyNumber");
            return (Criteria) this;
        }

        public Criteria andSupplyNumberIn(List<String> values) {
            addCriterion("supply_number in", values, "supplyNumber");
            return (Criteria) this;
        }

        public Criteria andSupplyNumberNotIn(List<String> values) {
            addCriterion("supply_number not in", values, "supplyNumber");
            return (Criteria) this;
        }

        public Criteria andSupplyNumberBetween(String value1, String value2) {
            addCriterion("supply_number between", value1, value2, "supplyNumber");
            return (Criteria) this;
        }

        public Criteria andSupplyNumberNotBetween(String value1, String value2) {
            addCriterion("supply_number not between", value1, value2, "supplyNumber");
            return (Criteria) this;
        }

        public Criteria andSupplyPositionIsNull() {
            addCriterion("supply_position is null");
            return (Criteria) this;
        }

        public Criteria andSupplyPositionIsNotNull() {
            addCriterion("supply_position is not null");
            return (Criteria) this;
        }

        public Criteria andSupplyPositionEqualTo(String value) {
            addCriterion("supply_position =", value, "supplyPosition");
            return (Criteria) this;
        }

        public Criteria andSupplyPositionNotEqualTo(String value) {
            addCriterion("supply_position <>", value, "supplyPosition");
            return (Criteria) this;
        }

        public Criteria andSupplyPositionGreaterThan(String value) {
            addCriterion("supply_position >", value, "supplyPosition");
            return (Criteria) this;
        }

        public Criteria andSupplyPositionGreaterThanOrEqualTo(String value) {
            addCriterion("supply_position >=", value, "supplyPosition");
            return (Criteria) this;
        }

        public Criteria andSupplyPositionLessThan(String value) {
            addCriterion("supply_position <", value, "supplyPosition");
            return (Criteria) this;
        }

        public Criteria andSupplyPositionLessThanOrEqualTo(String value) {
            addCriterion("supply_position <=", value, "supplyPosition");
            return (Criteria) this;
        }

        public Criteria andSupplyPositionLike(String value) {
            addCriterion("supply_position like", value, "supplyPosition");
            return (Criteria) this;
        }

        public Criteria andSupplyPositionNotLike(String value) {
            addCriterion("supply_position not like", value, "supplyPosition");
            return (Criteria) this;
        }

        public Criteria andSupplyPositionIn(List<String> values) {
            addCriterion("supply_position in", values, "supplyPosition");
            return (Criteria) this;
        }

        public Criteria andSupplyPositionNotIn(List<String> values) {
            addCriterion("supply_position not in", values, "supplyPosition");
            return (Criteria) this;
        }

        public Criteria andSupplyPositionBetween(String value1, String value2) {
            addCriterion("supply_position between", value1, value2, "supplyPosition");
            return (Criteria) this;
        }

        public Criteria andSupplyPositionNotBetween(String value1, String value2) {
            addCriterion("supply_position not between", value1, value2, "supplyPosition");
            return (Criteria) this;
        }

        public Criteria andSupplyStatusIsNull() {
            addCriterion("supply_status is null");
            return (Criteria) this;
        }

        public Criteria andSupplyStatusIsNotNull() {
            addCriterion("supply_status is not null");
            return (Criteria) this;
        }

        public Criteria andSupplyStatusEqualTo(Byte value) {
            addCriterion("supply_status =", value, "supplyStatus");
            return (Criteria) this;
        }

        public Criteria andSupplyStatusNotEqualTo(Byte value) {
            addCriterion("supply_status <>", value, "supplyStatus");
            return (Criteria) this;
        }

        public Criteria andSupplyStatusGreaterThan(Byte value) {
            addCriterion("supply_status >", value, "supplyStatus");
            return (Criteria) this;
        }

        public Criteria andSupplyStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("supply_status >=", value, "supplyStatus");
            return (Criteria) this;
        }

        public Criteria andSupplyStatusLessThan(Byte value) {
            addCriterion("supply_status <", value, "supplyStatus");
            return (Criteria) this;
        }

        public Criteria andSupplyStatusLessThanOrEqualTo(Byte value) {
            addCriterion("supply_status <=", value, "supplyStatus");
            return (Criteria) this;
        }

        public Criteria andSupplyStatusIn(List<Byte> values) {
            addCriterion("supply_status in", values, "supplyStatus");
            return (Criteria) this;
        }

        public Criteria andSupplyStatusNotIn(List<Byte> values) {
            addCriterion("supply_status not in", values, "supplyStatus");
            return (Criteria) this;
        }

        public Criteria andSupplyStatusBetween(Byte value1, Byte value2) {
            addCriterion("supply_status between", value1, value2, "supplyStatus");
            return (Criteria) this;
        }

        public Criteria andSupplyStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("supply_status not between", value1, value2, "supplyStatus");
            return (Criteria) this;
        }

        public Criteria andSupplyBuyerIsNull() {
            addCriterion("supply_buyer is null");
            return (Criteria) this;
        }

        public Criteria andSupplyBuyerIsNotNull() {
            addCriterion("supply_buyer is not null");
            return (Criteria) this;
        }

        public Criteria andSupplyBuyerEqualTo(String value) {
            addCriterion("supply_buyer =", value, "supplyBuyer");
            return (Criteria) this;
        }

        public Criteria andSupplyBuyerNotEqualTo(String value) {
            addCriterion("supply_buyer <>", value, "supplyBuyer");
            return (Criteria) this;
        }

        public Criteria andSupplyBuyerGreaterThan(String value) {
            addCriterion("supply_buyer >", value, "supplyBuyer");
            return (Criteria) this;
        }

        public Criteria andSupplyBuyerGreaterThanOrEqualTo(String value) {
            addCriterion("supply_buyer >=", value, "supplyBuyer");
            return (Criteria) this;
        }

        public Criteria andSupplyBuyerLessThan(String value) {
            addCriterion("supply_buyer <", value, "supplyBuyer");
            return (Criteria) this;
        }

        public Criteria andSupplyBuyerLessThanOrEqualTo(String value) {
            addCriterion("supply_buyer <=", value, "supplyBuyer");
            return (Criteria) this;
        }

        public Criteria andSupplyBuyerLike(String value) {
            addCriterion("supply_buyer like", value, "supplyBuyer");
            return (Criteria) this;
        }

        public Criteria andSupplyBuyerNotLike(String value) {
            addCriterion("supply_buyer not like", value, "supplyBuyer");
            return (Criteria) this;
        }

        public Criteria andSupplyBuyerIn(List<String> values) {
            addCriterion("supply_buyer in", values, "supplyBuyer");
            return (Criteria) this;
        }

        public Criteria andSupplyBuyerNotIn(List<String> values) {
            addCriterion("supply_buyer not in", values, "supplyBuyer");
            return (Criteria) this;
        }

        public Criteria andSupplyBuyerBetween(String value1, String value2) {
            addCriterion("supply_buyer between", value1, value2, "supplyBuyer");
            return (Criteria) this;
        }

        public Criteria andSupplyBuyerNotBetween(String value1, String value2) {
            addCriterion("supply_buyer not between", value1, value2, "supplyBuyer");
            return (Criteria) this;
        }

        public Criteria andSupplyBorrowerIsNull() {
            addCriterion("supply_borrower is null");
            return (Criteria) this;
        }

        public Criteria andSupplyBorrowerIsNotNull() {
            addCriterion("supply_borrower is not null");
            return (Criteria) this;
        }

        public Criteria andSupplyBorrowerEqualTo(String value) {
            addCriterion("supply_borrower =", value, "supplyBorrower");
            return (Criteria) this;
        }

        public Criteria andSupplyBorrowerNotEqualTo(String value) {
            addCriterion("supply_borrower <>", value, "supplyBorrower");
            return (Criteria) this;
        }

        public Criteria andSupplyBorrowerGreaterThan(String value) {
            addCriterion("supply_borrower >", value, "supplyBorrower");
            return (Criteria) this;
        }

        public Criteria andSupplyBorrowerGreaterThanOrEqualTo(String value) {
            addCriterion("supply_borrower >=", value, "supplyBorrower");
            return (Criteria) this;
        }

        public Criteria andSupplyBorrowerLessThan(String value) {
            addCriterion("supply_borrower <", value, "supplyBorrower");
            return (Criteria) this;
        }

        public Criteria andSupplyBorrowerLessThanOrEqualTo(String value) {
            addCriterion("supply_borrower <=", value, "supplyBorrower");
            return (Criteria) this;
        }

        public Criteria andSupplyBorrowerLike(String value) {
            addCriterion("supply_borrower like", value, "supplyBorrower");
            return (Criteria) this;
        }

        public Criteria andSupplyBorrowerNotLike(String value) {
            addCriterion("supply_borrower not like", value, "supplyBorrower");
            return (Criteria) this;
        }

        public Criteria andSupplyBorrowerIn(List<String> values) {
            addCriterion("supply_borrower in", values, "supplyBorrower");
            return (Criteria) this;
        }

        public Criteria andSupplyBorrowerNotIn(List<String> values) {
            addCriterion("supply_borrower not in", values, "supplyBorrower");
            return (Criteria) this;
        }

        public Criteria andSupplyBorrowerBetween(String value1, String value2) {
            addCriterion("supply_borrower between", value1, value2, "supplyBorrower");
            return (Criteria) this;
        }

        public Criteria andSupplyBorrowerNotBetween(String value1, String value2) {
            addCriterion("supply_borrower not between", value1, value2, "supplyBorrower");
            return (Criteria) this;
        }

        public Criteria andSupplyMarkIsNull() {
            addCriterion("supply_mark is null");
            return (Criteria) this;
        }

        public Criteria andSupplyMarkIsNotNull() {
            addCriterion("supply_mark is not null");
            return (Criteria) this;
        }

        public Criteria andSupplyMarkEqualTo(String value) {
            addCriterion("supply_mark =", value, "supplyMark");
            return (Criteria) this;
        }

        public Criteria andSupplyMarkNotEqualTo(String value) {
            addCriterion("supply_mark <>", value, "supplyMark");
            return (Criteria) this;
        }

        public Criteria andSupplyMarkGreaterThan(String value) {
            addCriterion("supply_mark >", value, "supplyMark");
            return (Criteria) this;
        }

        public Criteria andSupplyMarkGreaterThanOrEqualTo(String value) {
            addCriterion("supply_mark >=", value, "supplyMark");
            return (Criteria) this;
        }

        public Criteria andSupplyMarkLessThan(String value) {
            addCriterion("supply_mark <", value, "supplyMark");
            return (Criteria) this;
        }

        public Criteria andSupplyMarkLessThanOrEqualTo(String value) {
            addCriterion("supply_mark <=", value, "supplyMark");
            return (Criteria) this;
        }

        public Criteria andSupplyMarkLike(String value) {
            addCriterion("supply_mark like", value, "supplyMark");
            return (Criteria) this;
        }

        public Criteria andSupplyMarkNotLike(String value) {
            addCriterion("supply_mark not like", value, "supplyMark");
            return (Criteria) this;
        }

        public Criteria andSupplyMarkIn(List<String> values) {
            addCriterion("supply_mark in", values, "supplyMark");
            return (Criteria) this;
        }

        public Criteria andSupplyMarkNotIn(List<String> values) {
            addCriterion("supply_mark not in", values, "supplyMark");
            return (Criteria) this;
        }

        public Criteria andSupplyMarkBetween(String value1, String value2) {
            addCriterion("supply_mark between", value1, value2, "supplyMark");
            return (Criteria) this;
        }

        public Criteria andSupplyMarkNotBetween(String value1, String value2) {
            addCriterion("supply_mark not between", value1, value2, "supplyMark");
            return (Criteria) this;
        }

        public Criteria andSupplyBorrowTimeIsNull() {
            addCriterion("supply_borrow_time is null");
            return (Criteria) this;
        }

        public Criteria andSupplyBorrowTimeIsNotNull() {
            addCriterion("supply_borrow_time is not null");
            return (Criteria) this;
        }

        public Criteria andSupplyBorrowTimeEqualTo(Date value) {
            addCriterion("supply_borrow_time =", value, "supplyBorrowTime");
            return (Criteria) this;
        }

        public Criteria andSupplyBorrowTimeNotEqualTo(Date value) {
            addCriterion("supply_borrow_time <>", value, "supplyBorrowTime");
            return (Criteria) this;
        }

        public Criteria andSupplyBorrowTimeGreaterThan(Date value) {
            addCriterion("supply_borrow_time >", value, "supplyBorrowTime");
            return (Criteria) this;
        }

        public Criteria andSupplyBorrowTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("supply_borrow_time >=", value, "supplyBorrowTime");
            return (Criteria) this;
        }

        public Criteria andSupplyBorrowTimeLessThan(Date value) {
            addCriterion("supply_borrow_time <", value, "supplyBorrowTime");
            return (Criteria) this;
        }

        public Criteria andSupplyBorrowTimeLessThanOrEqualTo(Date value) {
            addCriterion("supply_borrow_time <=", value, "supplyBorrowTime");
            return (Criteria) this;
        }

        public Criteria andSupplyBorrowTimeIn(List<Date> values) {
            addCriterion("supply_borrow_time in", values, "supplyBorrowTime");
            return (Criteria) this;
        }

        public Criteria andSupplyBorrowTimeNotIn(List<Date> values) {
            addCriterion("supply_borrow_time not in", values, "supplyBorrowTime");
            return (Criteria) this;
        }

        public Criteria andSupplyBorrowTimeBetween(Date value1, Date value2) {
            addCriterion("supply_borrow_time between", value1, value2, "supplyBorrowTime");
            return (Criteria) this;
        }

        public Criteria andSupplyBorrowTimeNotBetween(Date value1, Date value2) {
            addCriterion("supply_borrow_time not between", value1, value2, "supplyBorrowTime");
            return (Criteria) this;
        }

        public Criteria andSupplyBuyTimeIsNull() {
            addCriterion("supply_buy_time is null");
            return (Criteria) this;
        }

        public Criteria andSupplyBuyTimeIsNotNull() {
            addCriterion("supply_buy_time is not null");
            return (Criteria) this;
        }

        public Criteria andSupplyBuyTimeEqualTo(Date value) {
            addCriterion("supply_buy_time =", value, "supplyBuyTime");
            return (Criteria) this;
        }

        public Criteria andSupplyBuyTimeNotEqualTo(Date value) {
            addCriterion("supply_buy_time <>", value, "supplyBuyTime");
            return (Criteria) this;
        }

        public Criteria andSupplyBuyTimeGreaterThan(Date value) {
            addCriterion("supply_buy_time >", value, "supplyBuyTime");
            return (Criteria) this;
        }

        public Criteria andSupplyBuyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("supply_buy_time >=", value, "supplyBuyTime");
            return (Criteria) this;
        }

        public Criteria andSupplyBuyTimeLessThan(Date value) {
            addCriterion("supply_buy_time <", value, "supplyBuyTime");
            return (Criteria) this;
        }

        public Criteria andSupplyBuyTimeLessThanOrEqualTo(Date value) {
            addCriterion("supply_buy_time <=", value, "supplyBuyTime");
            return (Criteria) this;
        }

        public Criteria andSupplyBuyTimeIn(List<Date> values) {
            addCriterion("supply_buy_time in", values, "supplyBuyTime");
            return (Criteria) this;
        }

        public Criteria andSupplyBuyTimeNotIn(List<Date> values) {
            addCriterion("supply_buy_time not in", values, "supplyBuyTime");
            return (Criteria) this;
        }

        public Criteria andSupplyBuyTimeBetween(Date value1, Date value2) {
            addCriterion("supply_buy_time between", value1, value2, "supplyBuyTime");
            return (Criteria) this;
        }

        public Criteria andSupplyBuyTimeNotBetween(Date value1, Date value2) {
            addCriterion("supply_buy_time not between", value1, value2, "supplyBuyTime");
            return (Criteria) this;
        }

        public Criteria andSupplyCostIsNull() {
            addCriterion("supply_cost is null");
            return (Criteria) this;
        }

        public Criteria andSupplyCostIsNotNull() {
            addCriterion("supply_cost is not null");
            return (Criteria) this;
        }

        public Criteria andSupplyCostEqualTo(String value) {
            addCriterion("supply_cost =", value, "supplyCost");
            return (Criteria) this;
        }

        public Criteria andSupplyCostNotEqualTo(String value) {
            addCriterion("supply_cost <>", value, "supplyCost");
            return (Criteria) this;
        }

        public Criteria andSupplyCostGreaterThan(String value) {
            addCriterion("supply_cost >", value, "supplyCost");
            return (Criteria) this;
        }

        public Criteria andSupplyCostGreaterThanOrEqualTo(String value) {
            addCriterion("supply_cost >=", value, "supplyCost");
            return (Criteria) this;
        }

        public Criteria andSupplyCostLessThan(String value) {
            addCriterion("supply_cost <", value, "supplyCost");
            return (Criteria) this;
        }

        public Criteria andSupplyCostLessThanOrEqualTo(String value) {
            addCriterion("supply_cost <=", value, "supplyCost");
            return (Criteria) this;
        }

        public Criteria andSupplyCostLike(String value) {
            addCriterion("supply_cost like", value, "supplyCost");
            return (Criteria) this;
        }

        public Criteria andSupplyCostNotLike(String value) {
            addCriterion("supply_cost not like", value, "supplyCost");
            return (Criteria) this;
        }

        public Criteria andSupplyCostIn(List<String> values) {
            addCriterion("supply_cost in", values, "supplyCost");
            return (Criteria) this;
        }

        public Criteria andSupplyCostNotIn(List<String> values) {
            addCriterion("supply_cost not in", values, "supplyCost");
            return (Criteria) this;
        }

        public Criteria andSupplyCostBetween(String value1, String value2) {
            addCriterion("supply_cost between", value1, value2, "supplyCost");
            return (Criteria) this;
        }

        public Criteria andSupplyCostNotBetween(String value1, String value2) {
            addCriterion("supply_cost not between", value1, value2, "supplyCost");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_supply
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_supply
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}