package mybatis.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_supply
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class SysSupply {
    @Override
	public String toString() {
		return "SysSupply [id=" + id + ", supplyName=" + supplyName + ", supplyNumber=" + supplyNumber
				+ ", supplyPosition=" + supplyPosition + ", supplyStatus=" + supplyStatus + ", supplyBuyer="
				+ supplyBuyer + ", supplyBorrower=" + supplyBorrower + ", supplyMark=" + supplyMark
				+ ", supplyBorrowTime=" + supplyBorrowTime + ", supplyBuyTime=" + supplyBuyTime + ", supplyCost="
				+ supplyCost + "]\n";
	}

	/**
     * Database Column Remarks:
     *   编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supply.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supply.supply_name
     *
     * @mbggenerated
     */
    private String supplyName;

    /**
     * Database Column Remarks:
     *   型号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supply.supply_number
     *
     * @mbggenerated
     */
    private String supplyNumber;

    /**
     * Database Column Remarks:
     *   存放位置
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supply.supply_position
     *
     * @mbggenerated
     */
    private String supplyPosition;

    /**
     * Database Column Remarks:
     *   -3申请/-2失败/-1成功/1还在/0借出
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supply.supply_status
     *
     * @mbggenerated
     */
    private Byte supplyStatus;

    /**
     * Database Column Remarks:
     *   购买人 外键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supply.supply_buyer
     *
     * @mbggenerated
     */
    private String supplyBuyer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supply.supply_borrower
     *
     * @mbggenerated
     */
    private String supplyBorrower;

    /**
     * Database Column Remarks:
     *   备注：申请理由or预计归还时间or其他
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supply.supply_mark
     *
     * @mbggenerated
     */
    private String supplyMark;

    /**
     * Database Column Remarks:
     *   借用时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supply.supply_borrow_time
     *
     * @mbggenerated
     */
    private Date supplyBorrowTime;

    /**
     * Database Column Remarks:
     *   购买时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supply.supply_buy_time
     *
     * @mbggenerated
     */
    private Date supplyBuyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_supply.supply_cost
     *
     * @mbggenerated
     */
    private String supplyCost;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supply.id
     *
     * @return the value of sys_supply.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supply.id
     *
     * @param id the value for sys_supply.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supply.supply_name
     *
     * @return the value of sys_supply.supply_name
     *
     * @mbggenerated
     */
    public String getSupplyName() {
        return supplyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supply.supply_name
     *
     * @param supplyName the value for sys_supply.supply_name
     *
     * @mbggenerated
     */
    public void setSupplyName(String supplyName) {
        this.supplyName = supplyName == null ? null : supplyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supply.supply_number
     *
     * @return the value of sys_supply.supply_number
     *
     * @mbggenerated
     */
    public String getSupplyNumber() {
        return supplyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supply.supply_number
     *
     * @param supplyNumber the value for sys_supply.supply_number
     *
     * @mbggenerated
     */
    public void setSupplyNumber(String supplyNumber) {
        this.supplyNumber = supplyNumber == null ? null : supplyNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supply.supply_position
     *
     * @return the value of sys_supply.supply_position
     *
     * @mbggenerated
     */
    public String getSupplyPosition() {
        return supplyPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supply.supply_position
     *
     * @param supplyPosition the value for sys_supply.supply_position
     *
     * @mbggenerated
     */
    public void setSupplyPosition(String supplyPosition) {
        this.supplyPosition = supplyPosition == null ? null : supplyPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supply.supply_status
     *
     * @return the value of sys_supply.supply_status
     *
     * @mbggenerated
     */
    public Byte getSupplyStatus() {
        return supplyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supply.supply_status
     *
     * @param supplyStatus the value for sys_supply.supply_status
     *
     * @mbggenerated
     */
    public void setSupplyStatus(Byte supplyStatus) {
        this.supplyStatus = supplyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supply.supply_buyer
     *
     * @return the value of sys_supply.supply_buyer
     *
     * @mbggenerated
     */
    public String getSupplyBuyer() {
        return supplyBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supply.supply_buyer
     *
     * @param supplyBuyer the value for sys_supply.supply_buyer
     *
     * @mbggenerated
     */
    public void setSupplyBuyer(String supplyBuyer) {
        this.supplyBuyer = supplyBuyer == null ? null : supplyBuyer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supply.supply_borrower
     *
     * @return the value of sys_supply.supply_borrower
     *
     * @mbggenerated
     */
    public String getSupplyBorrower() {
        return supplyBorrower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supply.supply_borrower
     *
     * @param supplyBorrower the value for sys_supply.supply_borrower
     *
     * @mbggenerated
     */
    public void setSupplyBorrower(String supplyBorrower) {
        this.supplyBorrower = supplyBorrower == null ? null : supplyBorrower.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supply.supply_mark
     *
     * @return the value of sys_supply.supply_mark
     *
     * @mbggenerated
     */
    public String getSupplyMark() {
        return supplyMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supply.supply_mark
     *
     * @param supplyMark the value for sys_supply.supply_mark
     *
     * @mbggenerated
     */
    public void setSupplyMark(String supplyMark) {
        this.supplyMark = supplyMark == null ? null : supplyMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supply.supply_borrow_time
     *
     * @return the value of sys_supply.supply_borrow_time
     *
     * @mbggenerated
     */
    public Date getSupplyBorrowTime() {
        return supplyBorrowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supply.supply_borrow_time
     *
     * @param supplyBorrowTime the value for sys_supply.supply_borrow_time
     *
     * @mbggenerated
     */
    public void setSupplyBorrowTime(Date supplyBorrowTime) {
        this.supplyBorrowTime = supplyBorrowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supply.supply_buy_time
     *
     * @return the value of sys_supply.supply_buy_time
     *
     * @mbggenerated
     */
    public Date getSupplyBuyTime() {
        return supplyBuyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supply.supply_buy_time
     *
     * @param supplyBuyTime the value for sys_supply.supply_buy_time
     *
     * @mbggenerated
     */
    public void setSupplyBuyTime(Date supplyBuyTime) {
        this.supplyBuyTime = supplyBuyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_supply.supply_cost
     *
     * @return the value of sys_supply.supply_cost
     *
     * @mbggenerated
     */
    public String getSupplyCost() {
        return supplyCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_supply.supply_cost
     *
     * @param supplyCost the value for sys_supply.supply_cost
     *
     * @mbggenerated
     */
    public void setSupplyCost(String supplyCost) {
        this.supplyCost = supplyCost == null ? null : supplyCost.trim();
    }
}