package mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysTaskExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    public SysTaskExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTaskPubTimeIsNull() {
            addCriterion("task_pub_time is null");
            return (Criteria) this;
        }

        public Criteria andTaskPubTimeIsNotNull() {
            addCriterion("task_pub_time is not null");
            return (Criteria) this;
        }

        public Criteria andTaskPubTimeEqualTo(Date value) {
            addCriterion("task_pub_time =", value, "taskPubTime");
            return (Criteria) this;
        }

        public Criteria andTaskPubTimeNotEqualTo(Date value) {
            addCriterion("task_pub_time <>", value, "taskPubTime");
            return (Criteria) this;
        }

        public Criteria andTaskPubTimeGreaterThan(Date value) {
            addCriterion("task_pub_time >", value, "taskPubTime");
            return (Criteria) this;
        }

        public Criteria andTaskPubTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("task_pub_time >=", value, "taskPubTime");
            return (Criteria) this;
        }

        public Criteria andTaskPubTimeLessThan(Date value) {
            addCriterion("task_pub_time <", value, "taskPubTime");
            return (Criteria) this;
        }

        public Criteria andTaskPubTimeLessThanOrEqualTo(Date value) {
            addCriterion("task_pub_time <=", value, "taskPubTime");
            return (Criteria) this;
        }

        public Criteria andTaskPubTimeIn(List<Date> values) {
            addCriterion("task_pub_time in", values, "taskPubTime");
            return (Criteria) this;
        }

        public Criteria andTaskPubTimeNotIn(List<Date> values) {
            addCriterion("task_pub_time not in", values, "taskPubTime");
            return (Criteria) this;
        }

        public Criteria andTaskPubTimeBetween(Date value1, Date value2) {
            addCriterion("task_pub_time between", value1, value2, "taskPubTime");
            return (Criteria) this;
        }

        public Criteria andTaskPubTimeNotBetween(Date value1, Date value2) {
            addCriterion("task_pub_time not between", value1, value2, "taskPubTime");
            return (Criteria) this;
        }

        public Criteria andTaskEndTimeIsNull() {
            addCriterion("task_end_time is null");
            return (Criteria) this;
        }

        public Criteria andTaskEndTimeIsNotNull() {
            addCriterion("task_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andTaskEndTimeEqualTo(Date value) {
            addCriterion("task_end_time =", value, "taskEndTime");
            return (Criteria) this;
        }

        public Criteria andTaskEndTimeNotEqualTo(Date value) {
            addCriterion("task_end_time <>", value, "taskEndTime");
            return (Criteria) this;
        }

        public Criteria andTaskEndTimeGreaterThan(Date value) {
            addCriterion("task_end_time >", value, "taskEndTime");
            return (Criteria) this;
        }

        public Criteria andTaskEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("task_end_time >=", value, "taskEndTime");
            return (Criteria) this;
        }

        public Criteria andTaskEndTimeLessThan(Date value) {
            addCriterion("task_end_time <", value, "taskEndTime");
            return (Criteria) this;
        }

        public Criteria andTaskEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("task_end_time <=", value, "taskEndTime");
            return (Criteria) this;
        }

        public Criteria andTaskEndTimeIn(List<Date> values) {
            addCriterion("task_end_time in", values, "taskEndTime");
            return (Criteria) this;
        }

        public Criteria andTaskEndTimeNotIn(List<Date> values) {
            addCriterion("task_end_time not in", values, "taskEndTime");
            return (Criteria) this;
        }

        public Criteria andTaskEndTimeBetween(Date value1, Date value2) {
            addCriterion("task_end_time between", value1, value2, "taskEndTime");
            return (Criteria) this;
        }

        public Criteria andTaskEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("task_end_time not between", value1, value2, "taskEndTime");
            return (Criteria) this;
        }

        public Criteria andTaskAccountIsNull() {
            addCriterion("task_account is null");
            return (Criteria) this;
        }

        public Criteria andTaskAccountIsNotNull() {
            addCriterion("task_account is not null");
            return (Criteria) this;
        }

        public Criteria andTaskAccountEqualTo(String value) {
            addCriterion("task_account =", value, "taskAccount");
            return (Criteria) this;
        }

        public Criteria andTaskAccountNotEqualTo(String value) {
            addCriterion("task_account <>", value, "taskAccount");
            return (Criteria) this;
        }

        public Criteria andTaskAccountGreaterThan(String value) {
            addCriterion("task_account >", value, "taskAccount");
            return (Criteria) this;
        }

        public Criteria andTaskAccountGreaterThanOrEqualTo(String value) {
            addCriterion("task_account >=", value, "taskAccount");
            return (Criteria) this;
        }

        public Criteria andTaskAccountLessThan(String value) {
            addCriterion("task_account <", value, "taskAccount");
            return (Criteria) this;
        }

        public Criteria andTaskAccountLessThanOrEqualTo(String value) {
            addCriterion("task_account <=", value, "taskAccount");
            return (Criteria) this;
        }

        public Criteria andTaskAccountLike(String value) {
            addCriterion("task_account like", value, "taskAccount");
            return (Criteria) this;
        }

        public Criteria andTaskAccountNotLike(String value) {
            addCriterion("task_account not like", value, "taskAccount");
            return (Criteria) this;
        }

        public Criteria andTaskAccountIn(List<String> values) {
            addCriterion("task_account in", values, "taskAccount");
            return (Criteria) this;
        }

        public Criteria andTaskAccountNotIn(List<String> values) {
            addCriterion("task_account not in", values, "taskAccount");
            return (Criteria) this;
        }

        public Criteria andTaskAccountBetween(String value1, String value2) {
            addCriterion("task_account between", value1, value2, "taskAccount");
            return (Criteria) this;
        }

        public Criteria andTaskAccountNotBetween(String value1, String value2) {
            addCriterion("task_account not between", value1, value2, "taskAccount");
            return (Criteria) this;
        }

        public Criteria andTaskUserNameIsNull() {
            addCriterion("task_user_name is null");
            return (Criteria) this;
        }

        public Criteria andTaskUserNameIsNotNull() {
            addCriterion("task_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andTaskUserNameEqualTo(String value) {
            addCriterion("task_user_name =", value, "taskUserName");
            return (Criteria) this;
        }

        public Criteria andTaskUserNameNotEqualTo(String value) {
            addCriterion("task_user_name <>", value, "taskUserName");
            return (Criteria) this;
        }

        public Criteria andTaskUserNameGreaterThan(String value) {
            addCriterion("task_user_name >", value, "taskUserName");
            return (Criteria) this;
        }

        public Criteria andTaskUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("task_user_name >=", value, "taskUserName");
            return (Criteria) this;
        }

        public Criteria andTaskUserNameLessThan(String value) {
            addCriterion("task_user_name <", value, "taskUserName");
            return (Criteria) this;
        }

        public Criteria andTaskUserNameLessThanOrEqualTo(String value) {
            addCriterion("task_user_name <=", value, "taskUserName");
            return (Criteria) this;
        }

        public Criteria andTaskUserNameLike(String value) {
            addCriterion("task_user_name like", value, "taskUserName");
            return (Criteria) this;
        }

        public Criteria andTaskUserNameNotLike(String value) {
            addCriterion("task_user_name not like", value, "taskUserName");
            return (Criteria) this;
        }

        public Criteria andTaskUserNameIn(List<String> values) {
            addCriterion("task_user_name in", values, "taskUserName");
            return (Criteria) this;
        }

        public Criteria andTaskUserNameNotIn(List<String> values) {
            addCriterion("task_user_name not in", values, "taskUserName");
            return (Criteria) this;
        }

        public Criteria andTaskUserNameBetween(String value1, String value2) {
            addCriterion("task_user_name between", value1, value2, "taskUserName");
            return (Criteria) this;
        }

        public Criteria andTaskUserNameNotBetween(String value1, String value2) {
            addCriterion("task_user_name not between", value1, value2, "taskUserName");
            return (Criteria) this;
        }

        public Criteria andTaskNameIsNull() {
            addCriterion("task_name is null");
            return (Criteria) this;
        }

        public Criteria andTaskNameIsNotNull() {
            addCriterion("task_name is not null");
            return (Criteria) this;
        }

        public Criteria andTaskNameEqualTo(String value) {
            addCriterion("task_name =", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameNotEqualTo(String value) {
            addCriterion("task_name <>", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameGreaterThan(String value) {
            addCriterion("task_name >", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameGreaterThanOrEqualTo(String value) {
            addCriterion("task_name >=", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameLessThan(String value) {
            addCriterion("task_name <", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameLessThanOrEqualTo(String value) {
            addCriterion("task_name <=", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameLike(String value) {
            addCriterion("task_name like", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameNotLike(String value) {
            addCriterion("task_name not like", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameIn(List<String> values) {
            addCriterion("task_name in", values, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameNotIn(List<String> values) {
            addCriterion("task_name not in", values, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameBetween(String value1, String value2) {
            addCriterion("task_name between", value1, value2, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameNotBetween(String value1, String value2) {
            addCriterion("task_name not between", value1, value2, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskGroupIsNull() {
            addCriterion("task_group is null");
            return (Criteria) this;
        }

        public Criteria andTaskGroupIsNotNull() {
            addCriterion("task_group is not null");
            return (Criteria) this;
        }

        public Criteria andTaskGroupEqualTo(String value) {
            addCriterion("task_group =", value, "taskGroup");
            return (Criteria) this;
        }

        public Criteria andTaskGroupNotEqualTo(String value) {
            addCriterion("task_group <>", value, "taskGroup");
            return (Criteria) this;
        }

        public Criteria andTaskGroupGreaterThan(String value) {
            addCriterion("task_group >", value, "taskGroup");
            return (Criteria) this;
        }

        public Criteria andTaskGroupGreaterThanOrEqualTo(String value) {
            addCriterion("task_group >=", value, "taskGroup");
            return (Criteria) this;
        }

        public Criteria andTaskGroupLessThan(String value) {
            addCriterion("task_group <", value, "taskGroup");
            return (Criteria) this;
        }

        public Criteria andTaskGroupLessThanOrEqualTo(String value) {
            addCriterion("task_group <=", value, "taskGroup");
            return (Criteria) this;
        }

        public Criteria andTaskGroupLike(String value) {
            addCriterion("task_group like", value, "taskGroup");
            return (Criteria) this;
        }

        public Criteria andTaskGroupNotLike(String value) {
            addCriterion("task_group not like", value, "taskGroup");
            return (Criteria) this;
        }

        public Criteria andTaskGroupIn(List<String> values) {
            addCriterion("task_group in", values, "taskGroup");
            return (Criteria) this;
        }

        public Criteria andTaskGroupNotIn(List<String> values) {
            addCriterion("task_group not in", values, "taskGroup");
            return (Criteria) this;
        }

        public Criteria andTaskGroupBetween(String value1, String value2) {
            addCriterion("task_group between", value1, value2, "taskGroup");
            return (Criteria) this;
        }

        public Criteria andTaskGroupNotBetween(String value1, String value2) {
            addCriterion("task_group not between", value1, value2, "taskGroup");
            return (Criteria) this;
        }

        public Criteria andTaskRemarkIsNull() {
            addCriterion("task_remark is null");
            return (Criteria) this;
        }

        public Criteria andTaskRemarkIsNotNull() {
            addCriterion("task_remark is not null");
            return (Criteria) this;
        }

        public Criteria andTaskRemarkEqualTo(String value) {
            addCriterion("task_remark =", value, "taskRemark");
            return (Criteria) this;
        }

        public Criteria andTaskRemarkNotEqualTo(String value) {
            addCriterion("task_remark <>", value, "taskRemark");
            return (Criteria) this;
        }

        public Criteria andTaskRemarkGreaterThan(String value) {
            addCriterion("task_remark >", value, "taskRemark");
            return (Criteria) this;
        }

        public Criteria andTaskRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("task_remark >=", value, "taskRemark");
            return (Criteria) this;
        }

        public Criteria andTaskRemarkLessThan(String value) {
            addCriterion("task_remark <", value, "taskRemark");
            return (Criteria) this;
        }

        public Criteria andTaskRemarkLessThanOrEqualTo(String value) {
            addCriterion("task_remark <=", value, "taskRemark");
            return (Criteria) this;
        }

        public Criteria andTaskRemarkLike(String value) {
            addCriterion("task_remark like", value, "taskRemark");
            return (Criteria) this;
        }

        public Criteria andTaskRemarkNotLike(String value) {
            addCriterion("task_remark not like", value, "taskRemark");
            return (Criteria) this;
        }

        public Criteria andTaskRemarkIn(List<String> values) {
            addCriterion("task_remark in", values, "taskRemark");
            return (Criteria) this;
        }

        public Criteria andTaskRemarkNotIn(List<String> values) {
            addCriterion("task_remark not in", values, "taskRemark");
            return (Criteria) this;
        }

        public Criteria andTaskRemarkBetween(String value1, String value2) {
            addCriterion("task_remark between", value1, value2, "taskRemark");
            return (Criteria) this;
        }

        public Criteria andTaskRemarkNotBetween(String value1, String value2) {
            addCriterion("task_remark not between", value1, value2, "taskRemark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_task
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}