package mybatis.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table task_submit_record
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class TaskSubmitRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_submit_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   作业号 外键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_submit_record.task_id
     *
     * @mbggenerated
     */
    private Integer taskId;

    /**
     * Database Column Remarks:
     *   提交人 外键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_submit_record.task_submit_account
     *
     * @mbggenerated
     */
    private String taskSubmitAccount;

    /**
     * Database Column Remarks:
     *   提交时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_submit_record.task_submit_time
     *
     * @mbggenerated
     */
    private Date taskSubmitTime;

    /**
     * Database Column Remarks:
     *   作业文件名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_submit_record.task_submit_name
     *
     * @mbggenerated
     */
    private String taskSubmitName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_submit_record.id
     *
     * @return the value of task_submit_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_submit_record.id
     *
     * @param id the value for task_submit_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_submit_record.task_id
     *
     * @return the value of task_submit_record.task_id
     *
     * @mbggenerated
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_submit_record.task_id
     *
     * @param taskId the value for task_submit_record.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_submit_record.task_submit_account
     *
     * @return the value of task_submit_record.task_submit_account
     *
     * @mbggenerated
     */
    public String getTaskSubmitAccount() {
        return taskSubmitAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_submit_record.task_submit_account
     *
     * @param taskSubmitAccount the value for task_submit_record.task_submit_account
     *
     * @mbggenerated
     */
    public void setTaskSubmitAccount(String taskSubmitAccount) {
        this.taskSubmitAccount = taskSubmitAccount == null ? null : taskSubmitAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_submit_record.task_submit_time
     *
     * @return the value of task_submit_record.task_submit_time
     *
     * @mbggenerated
     */
    public Date getTaskSubmitTime() {
        return taskSubmitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_submit_record.task_submit_time
     *
     * @param taskSubmitTime the value for task_submit_record.task_submit_time
     *
     * @mbggenerated
     */
    public void setTaskSubmitTime(Date taskSubmitTime) {
        this.taskSubmitTime = taskSubmitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_submit_record.task_submit_name
     *
     * @return the value of task_submit_record.task_submit_name
     *
     * @mbggenerated
     */
    public String getTaskSubmitName() {
        return taskSubmitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_submit_record.task_submit_name
     *
     * @param taskSubmitName the value for task_submit_record.task_submit_name
     *
     * @mbggenerated
     */
    public void setTaskSubmitName(String taskSubmitName) {
        this.taskSubmitName = taskSubmitName == null ? null : taskSubmitName.trim();
    }
}